### YamlMime:PowershellCmdlet
summary: |-
  Compute the information protection label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key/value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Test-MgSiteInformationProtectionPolicyLabelApplication](/powershell/module/Microsoft.Graph.Sites/Test-MgSiteInformationProtectionPolicyLabelApplication?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Sites
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IPaths2M9SewSitesSiteIdInformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>`: .
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[ContentInfo <IMicrosoftGraphContentInfo>]`: contentInfo
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Format <String>]`: contentFormat
      - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
      - `[Metadata <IMicrosoftGraphKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key/value pairs, where the key is the MSIP_Label_GUID_PropName.
        - `[Name <String>]`: Name for this key-value pair
        - `[Value <String>]`: Value for this key-value pair
      - `[State <String>]`: contentState
    - `[LabelingOptions <IMicrosoftGraphLabelingOptions>]`: labelingOptions
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[AssignmentMethod <String>]`: assignmentMethod
      - `[DowngradeJustification <IMicrosoftGraphDowngradeJustification>]`: downgradeJustification
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
        - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
      - `[ExtendedProperties <IMicrosoftGraphKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard MIP labeled metadata format as part of the label information.
      - `[LabelId <String>]`: The GUID of the label that should be applied to the information.

  `CONTENTINFO <IMicrosoftGraphContentInfo>`: contentInfo
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Format <String>]`: contentFormat
    - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
    - `[Metadata <IMicrosoftGraphKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key/value pairs, where the key is the MSIP_Label_GUID_PropName.
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[State <String>]`: contentState

  `INPUTOBJECT <ISitesIdentity>`: Identity Parameter
    - `[BaseItemId <String>]`: The unique identifier of baseItem
    - `[BitlockerRecoveryKeyId <String>]`: The unique identifier of bitlockerRecoveryKey
    - `[ColumnDefinitionId <String>]`: The unique identifier of columnDefinition
    - `[ColumnLinkId <String>]`: The unique identifier of columnLink
    - `[ContentTypeId <String>]`: The unique identifier of contentType
    - `[ContentTypeId1 <String>]`: The unique identifier of contentType
    - `[DataLossPreventionPolicyId <String>]`: The unique identifier of dataLossPreventionPolicy
    - `[DocumentSetVersionId <String>]`: The unique identifier of documentSetVersion
    - `[DriveId <String>]`: The unique identifier of drive
    - `[EndDateTime <String>]`: Usage: endDateTime='{endDateTime}'
    - `[GroupId <String>]`: The unique identifier of group
    - `[GroupId1 <String>]`: The unique identifier of group
    - `[HorizontalSectionColumnId <String>]`: The unique identifier of horizontalSectionColumn
    - `[HorizontalSectionId <String>]`: The unique identifier of horizontalSection
    - `[IncludePersonalNotebooks <Boolean?>]`: Usage: includePersonalNotebooks={includePersonalNotebooks}
    - `[InformationProtectionLabelId <String>]`: The unique identifier of informationProtectionLabel
    - `[Interval <String>]`: Usage: interval='{interval}'
    - `[ItemActivityId <String>]`: The unique identifier of itemActivity
    - `[ItemActivityOldId <String>]`: The unique identifier of itemActivityOLD
    - `[ItemActivityStatId <String>]`: The unique identifier of itemActivityStat
    - `[ListId <String>]`: The unique identifier of list
    - `[ListItemId <String>]`: The unique identifier of listItem
    - `[ListItemVersionId <String>]`: The unique identifier of listItemVersion
    - `[NotebookId <String>]`: The unique identifier of notebook
    - `[OnenoteOperationId <String>]`: The unique identifier of onenoteOperation
    - `[OnenotePageId <String>]`: The unique identifier of onenotePage
    - `[OnenoteResourceId <String>]`: The unique identifier of onenoteResource
    - `[OnenoteSectionId <String>]`: The unique identifier of onenoteSection
    - `[Path <String>]`: Usage: path='{path}'
    - `[PermissionId <String>]`: The unique identifier of permission
    - `[RelationId <String>]`: The unique identifier of relation
    - `[RichLongRunningOperationId <String>]`: The unique identifier of richLongRunningOperation
    - `[SectionGroupId <String>]`: The unique identifier of sectionGroup
    - `[SectionGroupId1 <String>]`: The unique identifier of sectionGroup
    - `[SensitivityLabelId <String>]`: The unique identifier of sensitivityLabel
    - `[SensitivityLabelId1 <String>]`: The unique identifier of sensitivityLabel
    - `[SetId <String>]`: The unique identifier of set
    - `[SetId1 <String>]`: The unique identifier of set
    - `[SiteId <String>]`: The unique identifier of site
    - `[SiteId1 <String>]`: The unique identifier of site
    - `[SitePageId <String>]`: The unique identifier of sitePage
    - `[StartDateTime <String>]`: Usage: startDateTime='{startDateTime}'
    - `[SubscriptionId <String>]`: The unique identifier of subscription
    - `[TermId <String>]`: The unique identifier of term
    - `[TermId1 <String>]`: The unique identifier of term
    - `[ThreatAssessmentRequestId <String>]`: The unique identifier of threatAssessmentRequest
    - `[ThreatAssessmentResultId <String>]`: The unique identifier of threatAssessmentResult
    - `[Token <String>]`: Usage: token='{token}'
    - `[UserId <String>]`: The unique identifier of user
    - `[WebPartId <String>]`: The unique identifier of webPart

  `LABELINGOPTIONS <IMicrosoftGraphLabelingOptions>`: labelingOptions
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[AssignmentMethod <String>]`: assignmentMethod
    - `[DowngradeJustification <IMicrosoftGraphDowngradeJustification>]`: downgradeJustification
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
      - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
    - `[ExtendedProperties <IMicrosoftGraphKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard MIP labeled metadata format as part of the label information.
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[LabelId <String>]`: The GUID of the label that should be applied to the information.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IPaths2M9SewSitesSiteIdInformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.ISitesIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphInformationProtectionAction" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Test-MgSiteInformationProtectionPolicyLabelApplication
  href: /powershell/module/Microsoft.Graph.Sites/Test-MgSiteInformationProtectionPolicyLabelApplication?view=graph-powershell-v1.0
syntaxes:
- >-
  Test-MgBetaSiteInformationProtectionPolicyLabelApplication -SiteId <String> [-AdditionalProperties <Hashtable>]

   [-ContentInfo <IMicrosoftGraphContentInfo>] [-LabelingOptions <IMicrosoftGraphLabelingOptions>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaSiteInformationProtectionPolicyLabelApplication -SiteId <String>

   -BodyParameter <IPaths2M9SewSitesSiteIdInformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaSiteInformationProtectionPolicyLabelApplication -InputObject <ISitesIdentity>

   [-AdditionalProperties <Hashtable>] [-ContentInfo <IMicrosoftGraphContentInfo>]

   [-LabelingOptions <IMicrosoftGraphLabelingOptions>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaSiteInformationProtectionPolicyLabelApplication -InputObject <ISitesIdentity>

   -BodyParameter <IPaths2M9SewSitesSiteIdInformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>

   [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IPaths2M9SewSitesSiteIdInformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    .
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphContentInfo" data-throw-if-not-resolved="False" />
  name: ContentInfo
  description: |+
    contentInfo
    To construct, see NOTES section for CONTENTINFO properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ISitesIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphLabelingOptions" data-throw-if-not-resolved="False" />
  name: LabelingOptions
  description: |+
    labelingOptions
    To construct, see NOTES section for LABELINGOPTIONS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SiteId
  isRequired: true
  description: |+
    The unique identifier of site

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Sites.Test-MgBetaSiteInformationProtectionPolicyLabelApplication
name: Test-MgBetaSiteInformationProtectionPolicyLabelApplication
description: |-
  Compute the information protection label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key/value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:
metadata:
  external help file: Microsoft.Graph.Beta.Sites-help.xml
  Module Name: Microsoft.Graph.Beta.Sites
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.sites/test-mgbetasiteinformationprotectionpolicylabelapplication
  schema: 2.0.0
