### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property simulationAutomations in security

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Update-MgBetaSecurityAttackSimulationAutomation](/powershell/module/Microsoft.Graph.Beta.Security/Update-MgBetaSecurityAttackSimulationAutomation?view=graph-powershell-beta)
module: Microsoft.Graph.Security
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphSimulationAutomation>`: simulationAutomation
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[CreatedBy <IMicrosoftGraphEmailIdentity>]`: emailIdentity
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
      - `[Id <String>]`: Unique identifier for the identity.
      - `[Email <String>]`: Email address of the user.
    - `[CreatedDateTime <DateTime?>]`: Date and time when the attack simulation automation was created.
    - `[Description <String>]`: Description of the attack simulation automation.
    - `[DisplayName <String>]`: Display name of the attack simulation automation. Supports $filter and $orderby.
    - `[LastModifiedBy <IMicrosoftGraphEmailIdentity>]`: emailIdentity
    - `[LastModifiedDateTime <DateTime?>]`: Date and time when the attack simulation automation was most recently modified.
    - `[LastRunDateTime <DateTime?>]`: Date and time of the latest run of the attack simulation automation.
    - `[NextRunDateTime <DateTime?>]`: Date and time of the upcoming run of the attack simulation automation.
    - `[Runs <IMicrosoftGraphSimulationAutomationRun[]>]`: A collection of simulation automation runs.
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[EndDateTime <DateTime?>]`: Date and time when the run ends in an attack simulation automation.
      - `[SimulationId <String>]`: Unique identifier for the attack simulation campaign initiated in the attack simulation automation run.
      - `[StartDateTime <DateTime?>]`: Date and time when the run starts in an attack simulation automation.
      - `[Status <String>]`: simulationAutomationRunStatus
    - `[Status <String>]`: simulationAutomationStatus

  `CREATEDBY <IMicrosoftGraphEmailIdentity>`: emailIdentity
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
    - `[Id <String>]`: Unique identifier for the identity.
    - `[Email <String>]`: Email address of the user.

  `INPUTOBJECT <ISecurityIdentity>`: Identity Parameter
    - `[AlertId <String>]`: The unique identifier of alert
    - `[ArticleId <String>]`: The unique identifier of article
    - `[ArticleIndicatorId <String>]`: The unique identifier of articleIndicator
    - `[CaseOperationId <String>]`: The unique identifier of caseOperation
    - `[DataSourceId <String>]`: The unique identifier of dataSource
    - `[EdiscoveryCaseId <String>]`: The unique identifier of ediscoveryCase
    - `[EdiscoveryCustodianId <String>]`: The unique identifier of ediscoveryCustodian
    - `[EdiscoveryNoncustodialDataSourceId <String>]`: The unique identifier of ediscoveryNoncustodialDataSource
    - `[EdiscoveryReviewSetId <String>]`: The unique identifier of ediscoveryReviewSet
    - `[EdiscoveryReviewSetQueryId <String>]`: The unique identifier of ediscoveryReviewSetQuery
    - `[EdiscoveryReviewTagId <String>]`: The unique identifier of ediscoveryReviewTag
    - `[EdiscoveryReviewTagId1 <String>]`: The unique identifier of ediscoveryReviewTag
    - `[EdiscoverySearchId <String>]`: The unique identifier of ediscoverySearch
    - `[HostComponentId <String>]`: The unique identifier of hostComponent
    - `[HostCookieId <String>]`: The unique identifier of hostCookie
    - `[HostId <String>]`: The unique identifier of host
    - `[HostTrackerId <String>]`: The unique identifier of hostTracker
    - `[IncidentId <String>]`: The unique identifier of incident
    - `[IntelligenceProfileId <String>]`: The unique identifier of intelligenceProfile
    - `[IntelligenceProfileIndicatorId <String>]`: The unique identifier of intelligenceProfileIndicator
    - `[PassiveDnsRecordId <String>]`: The unique identifier of passiveDnsRecord
    - `[RetentionEventId <String>]`: The unique identifier of retentionEvent
    - `[RetentionEventTypeId <String>]`: The unique identifier of retentionEventType
    - `[SecureScoreControlProfileId <String>]`: The unique identifier of secureScoreControlProfile
    - `[SecureScoreId <String>]`: The unique identifier of secureScore
    - `[SimulationAutomationId <String>]`: The unique identifier of simulationAutomation
    - `[SimulationAutomationRunId <String>]`: The unique identifier of simulationAutomationRun
    - `[SimulationId <String>]`: The unique identifier of simulation
    - `[SiteSourceId <String>]`: The unique identifier of siteSource
    - `[UnifiedGroupSourceId <String>]`: The unique identifier of unifiedGroupSource
    - `[UserSourceId <String>]`: The unique identifier of userSource
    - `[VulnerabilityComponentId <String>]`: The unique identifier of vulnerabilityComponent
    - `[VulnerabilityId <String>]`: The unique identifier of vulnerability

  `LASTMODIFIEDBY <IMicrosoftGraphEmailIdentity>`: emailIdentity
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
    - `[Id <String>]`: Unique identifier for the identity.
    - `[Email <String>]`: Email address of the user.

  `RUNS <IMicrosoftGraphSimulationAutomationRun[]>`: A collection of simulation automation runs.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[EndDateTime <DateTime?>]`: Date and time when the run ends in an attack simulation automation.
    - `[SimulationId <String>]`: Unique identifier for the attack simulation campaign initiated in the attack simulation automation run.
    - `[StartDateTime <DateTime?>]`: Date and time when the run starts in an attack simulation automation.
    - `[Status <String>]`: simulationAutomationRunStatus
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphSimulationAutomation" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.PowerShell.Models.ISecurityIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphSimulationAutomation" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBetaSecurityAttackSimulationAutomation
  href: /powershell/module/Microsoft.Graph.Beta.Security/Update-MgBetaSecurityAttackSimulationAutomation?view=graph-powershell-beta
syntaxes:
- >-
  Update-MgSecurityAttackSimulationAutomation -SimulationAutomationId <String>

   [-AdditionalProperties <Hashtable>] [-CreatedBy <IMicrosoftGraphEmailIdentity>] [-CreatedDateTime <DateTime>]

   [-Description <String>] [-DisplayName <String>] [-Id <String>]

   [-LastModifiedBy <IMicrosoftGraphEmailIdentity>] [-LastModifiedDateTime <DateTime>]

   [-LastRunDateTime <DateTime>] [-NextRunDateTime <DateTime>] [-Runs <IMicrosoftGraphSimulationAutomationRun[]>]

   [-Status <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgSecurityAttackSimulationAutomation -SimulationAutomationId <String>

   -BodyParameter <IMicrosoftGraphSimulationAutomation> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgSecurityAttackSimulationAutomation -InputObject <ISecurityIdentity>

   [-AdditionalProperties <Hashtable>] [-CreatedBy <IMicrosoftGraphEmailIdentity>] [-CreatedDateTime <DateTime>]

   [-Description <String>] [-DisplayName <String>] [-Id <String>]

   [-LastModifiedBy <IMicrosoftGraphEmailIdentity>] [-LastModifiedDateTime <DateTime>]

   [-LastRunDateTime <DateTime>] [-NextRunDateTime <DateTime>] [-Runs <IMicrosoftGraphSimulationAutomationRun[]>]

   [-Status <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgSecurityAttackSimulationAutomation -InputObject <ISecurityIdentity>

   -BodyParameter <IMicrosoftGraphSimulationAutomation> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphSimulationAutomation" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    simulationAutomation
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphEmailIdentity" data-throw-if-not-resolved="False" />
  name: CreatedBy
  description: |+
    emailIdentity
    To construct, see NOTES section for CREATEDBY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CreatedDateTime
  description: |+
    Date and time when the attack simulation automation was created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Description of the attack simulation automation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Display name of the attack simulation automation.
    Supports $filter and $orderby.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ISecurityIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphEmailIdentity" data-throw-if-not-resolved="False" />
  name: LastModifiedBy
  description: |+
    emailIdentity
    To construct, see NOTES section for LASTMODIFIEDBY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastModifiedDateTime
  description: |+
    Date and time when the attack simulation automation was most recently modified.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastRunDateTime
  description: |+
    Date and time of the latest run of the attack simulation automation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: NextRunDateTime
  description: |+
    Date and time of the upcoming run of the attack simulation automation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphSimulationAutomationRun" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Runs
  description: |+
    A collection of simulation automation runs.
    To construct, see NOTES section for RUNS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SimulationAutomationId
  isRequired: true
  description: |+
    The unique identifier of simulationAutomation

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Status
  description: |+
    simulationAutomationStatus

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Security.Update-MgSecurityAttackSimulationAutomation
name: Update-MgSecurityAttackSimulationAutomation
description: |-
  Update the navigation property simulationAutomations in security
metadata:
  external help file: Microsoft.Graph.Security-help.xml
  Module Name: Microsoft.Graph.Security
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.security/update-mgsecurityattacksimulationautomation
  schema: 2.0.0
