### YamlMime:PowershellCmdlet
summary: |-
  Compute the sensitivity label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key-value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Test-MgUserSecurityInformationProtectionSensitivityLabelApplication](/powershell/module/Microsoft.Graph.Users.Actions/Test-MgUserSecurityInformationProtectionSensitivityLabelApplication?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Users.Actions
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IPaths1Ssqny1UsersUserIdSecurityInformationprotectionSensitivitylabelsMicrosoftGraphSecurityEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>`: .
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[ContentInfo <IMicrosoftGraphSecurityContentInfo>]`: contentInfo
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[ContentFormat <String>]`: The format of the content to be labeled. Possible values are: file, email.
      - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
      - `[Metadata <IMicrosoftGraphSecurityKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key-value pairs, where the key is the MSIP_Label_GUID_PropName.
        - `[Name <String>]`: Name for this key-value pair.
        - `[Value <String>]`: Value for this key-value pair.
      - `[State <String>]`: contentState
    - `[LabelingOptions <IMicrosoftGraphSecurityLabelingOptions>]`: labelingOptions
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[AssignmentMethod <String>]`: assignmentMethod
      - `[DowngradeJustification <IMicrosoftGraphSecurityDowngradeJustification>]`: downgradeJustification
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
        - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
      - `[ExtendedProperties <IMicrosoftGraphSecurityKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard Microsoft Purview Information Protection labeled metadata format as part of the label information.
      - `[LabelId <String>]`: The GUID of the label that should be applied to the information.

  `CONTENTINFO <IMicrosoftGraphSecurityContentInfo>`: contentInfo
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[ContentFormat <String>]`: The format of the content to be labeled. Possible values are: file, email.
    - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
    - `[Metadata <IMicrosoftGraphSecurityKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key-value pairs, where the key is the MSIP_Label_GUID_PropName.
      - `[Name <String>]`: Name for this key-value pair.
      - `[Value <String>]`: Value for this key-value pair.
    - `[State <String>]`: contentState

  `INPUTOBJECT <IUsersActionsIdentity>`: Identity Parameter
    - `[AccessReviewInstanceId <String>]`: The unique identifier of accessReviewInstance
    - `[AccessReviewStageId <String>]`: The unique identifier of accessReviewStage
    - `[AppLogCollectionRequestId <String>]`: The unique identifier of appLogCollectionRequest
    - `[AuthenticationMethodId <String>]`: The unique identifier of authenticationMethod
    - `[CalendarId <String>]`: The unique identifier of calendar
    - `[ChatId <String>]`: The unique identifier of chat
    - `[ChatMessageId <String>]`: The unique identifier of chatMessage
    - `[ChatMessageId1 <String>]`: The unique identifier of chatMessage
    - `[CloudPcId <String>]`: The unique identifier of cloudPC
    - `[ContentTypeId <String>]`: The unique identifier of contentType
    - `[DeviceEnrollmentConfigurationId <String>]`: The unique identifier of deviceEnrollmentConfiguration
    - `[DeviceId <String>]`: The unique identifier of device
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DocumentSetVersionId <String>]`: The unique identifier of documentSetVersion
    - `[DriveId <String>]`: The unique identifier of drive
    - `[DriveItemId <String>]`: The unique identifier of driveItem
    - `[DriveItemVersionId <String>]`: The unique identifier of driveItemVersion
    - `[EventId <String>]`: The unique identifier of event
    - `[EventId1 <String>]`: The unique identifier of event
    - `[ListItemId <String>]`: The unique identifier of listItem
    - `[ListItemVersionId <String>]`: The unique identifier of listItemVersion
    - `[MailFolderId <String>]`: The unique identifier of mailFolder
    - `[MailFolderId1 <String>]`: The unique identifier of mailFolder
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[MessageId <String>]`: The unique identifier of message
    - `[MobileAppTroubleshootingEventId <String>]`: The unique identifier of mobileAppTroubleshootingEvent
    - `[NotebookId <String>]`: The unique identifier of notebook
    - `[OnenotePageId <String>]`: The unique identifier of onenotePage
    - `[OnenoteSectionId <String>]`: The unique identifier of onenoteSection
    - `[OutlookTaskFolderId <String>]`: The unique identifier of outlookTaskFolder
    - `[OutlookTaskGroupId <String>]`: The unique identifier of outlookTaskGroup
    - `[OutlookTaskId <String>]`: The unique identifier of outlookTask
    - `[PermissionId <String>]`: The unique identifier of permission
    - `[ResourceSpecificPermissionGrantId <String>]`: The unique identifier of resourceSpecificPermissionGrant
    - `[SensitivityLabelId <String>]`: The unique identifier of sensitivityLabel
    - `[SubscriptionId <String>]`: The unique identifier of subscription
    - `[TeamsAppInstallationId <String>]`: The unique identifier of teamsAppInstallation
    - `[TodoTaskId <String>]`: The unique identifier of todoTask
    - `[TodoTaskListId <String>]`: The unique identifier of todoTaskList
    - `[UserId <String>]`: The unique identifier of user

  `LABELINGOPTIONS <IMicrosoftGraphSecurityLabelingOptions>`: labelingOptions
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[AssignmentMethod <String>]`: assignmentMethod
    - `[DowngradeJustification <IMicrosoftGraphSecurityDowngradeJustification>]`: downgradeJustification
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
      - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
    - `[ExtendedProperties <IMicrosoftGraphSecurityKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard Microsoft Purview Information Protection labeled metadata format as part of the label information.
      - `[Name <String>]`: Name for this key-value pair.
      - `[Value <String>]`: Value for this key-value pair.
    - `[LabelId <String>]`: The GUID of the label that should be applied to the information.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IPaths1Ssqny1UsersUserIdSecurityInformationprotectionSensitivitylabelsMicrosoftGraphSecurityEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IUsersActionsIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphSecurityInformationProtectionAction" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Test-MgUserSecurityInformationProtectionSensitivityLabelApplication
  href: /powershell/module/Microsoft.Graph.Users.Actions/Test-MgUserSecurityInformationProtectionSensitivityLabelApplication?view=graph-powershell-v1.0
syntaxes:
- >-
  Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication -UserId <String>

   [-AdditionalProperties <Hashtable>] [-ContentInfo <IMicrosoftGraphSecurityContentInfo>]

   [-LabelingOptions <IMicrosoftGraphSecurityLabelingOptions>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication -UserId <String>

   -BodyParameter <IPaths1Ssqny1UsersUserIdSecurityInformationprotectionSensitivitylabelsMicrosoftGraphSecurityEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication -InputObject <IUsersActionsIdentity>

   [-AdditionalProperties <Hashtable>] [-ContentInfo <IMicrosoftGraphSecurityContentInfo>]

   [-LabelingOptions <IMicrosoftGraphSecurityLabelingOptions>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication -InputObject <IUsersActionsIdentity>

   -BodyParameter <IPaths1Ssqny1UsersUserIdSecurityInformationprotectionSensitivitylabelsMicrosoftGraphSecurityEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Using the Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Users.Actions
    $params = @{
    	ContentInfo = @{
    		"@odata.type" = "#microsoft.graph.security.contentInfo"
    		"Format@odata.type" = "#microsoft.graph.security.contentFormat"
    		ContentFormat = "File"
    		Format = "default"
    		Identifier = $null
    		"State@odata.type" = "#microsoft.graph.security.contentState"
    		State = "rest"
    		"Metadata@odata.type" = "#Collection(microsoft.graph.security.keyValuePair)"
    		Metadata = @(
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_Enabled"
    				Value = "True"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_Method"
    				Value = "Standard"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_SetDate"
    				Value = "1/1/0001 12:00:00 AM"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_SiteId"
    				Value = "cfa4cf1d-a337-4481-aa99-19d8f3d63f7c"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_Name"
    				Value = "LabelScopedToBob_Tests"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_ContentBits"
    				Value = "0"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.security.keyValuePair"
    				Name = "MSIP_Label_3a80e051-487c-40d4-b491-73ad25d997e6_ActionId"
    				Value = "00000000-0000-0000-0000-000000000000"
    			}
    		)
    	}
    	LabelingOptions = @{
    		"@odata.type" = "#microsoft.graph.security.labelingOptions"
    		"AssignmentMethod@odata.type" = "#microsoft.graph.security.assignmentMethod"
    		AssignmentMethod = "standard"
    		"LabelId@odata.type" = "#Guid"
    		LabelId = "836ff34f-b604-4a62-a68c-d6be4205d569"
    		DowngradeJustification = @{
    			JustificationMessage = "Justified"
    			IsDowngradeJustified = $true
    		}
    		"ExtendedProperties@odata.type" = "#Collection(microsoft.graph.security.keyValuePair)"
    		ExtendedProperties = @(
    		)
    	}
    }
    Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication -UserId $userId -BodyParameter $params
  description: |-
    This example shows how to use the Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IPaths1Ssqny1UsersUserIdSecurityInformationprotectionSensitivitylabelsMicrosoftGraphSecurityEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    .
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphSecurityContentInfo" data-throw-if-not-resolved="False" />
  name: ContentInfo
  description: |+
    contentInfo
    To construct, see NOTES section for CONTENTINFO properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IUsersActionsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphSecurityLabelingOptions" data-throw-if-not-resolved="False" />
  name: LabelingOptions
  description: |+
    labelingOptions
    To construct, see NOTES section for LABELINGOPTIONS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserId
  isRequired: true
  description: |+
    The unique identifier of user

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Users.Actions.Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication
name: Test-MgBetaUserSecurityInformationProtectionSensitivityLabelApplication
description: |-
  Compute the sensitivity label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key-value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:
metadata:
  external help file: Microsoft.Graph.Beta.Users.Actions-help.xml
  Module Name: Microsoft.Graph.Beta.Users.Actions
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.users.actions/test-mgbetausersecurityinformationprotectionsensitivitylabelapplication
  schema: 2.0.0
