### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to deviceConfigurationRestrictedAppsViolations for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementDeviceConfigurationRestrictedAppViolation](/powershell/module/Microsoft.Graph.DeviceManagement.Administration/New-MgDeviceManagementDeviceConfigurationRestrictedAppViolation?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement.Administration
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphRestrictedAppsViolation>`: Violation of restricted apps configuration profile per device per user
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[DeviceConfigurationId <String>]`: Device configuration profile unique identifier, must be Guid
    - `[DeviceConfigurationName <String>]`: Device configuration profile name
    - `[DeviceName <String>]`: Device name
    - `[ManagedDeviceId <String>]`: Managed device unique identifier, must be Guid
    - `[PlatformType <PolicyPlatformType?>]`: Supported platform types for policies.
    - `[RestrictedApps <IMicrosoftGraphManagedDeviceReportedApp[]>]`: List of violated restricted apps
      - `[AppId <String>]`: The application or bundle identifier of the application
    - `[RestrictedAppsState <RestrictedAppsState?>]`: Restricted apps state
    - `[UserId <String>]`: User unique identifier, must be Guid
    - `[UserName <String>]`: User name

  `RESTRICTEDAPPS <IMicrosoftGraphManagedDeviceReportedApp[]>`: List of violated restricted apps
    - `[AppId <String>]`: The application or bundle identifier of the application
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphRestrictedAppsViolation" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphRestrictedAppsViolation" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementDeviceConfigurationRestrictedAppViolation
  href: /powershell/module/Microsoft.Graph.DeviceManagement.Administration/New-MgDeviceManagementDeviceConfigurationRestrictedAppViolation?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementDeviceConfigurationRestrictedAppViolation [-AdditionalProperties <Hashtable>]

   [-DeviceConfigurationId <String>] [-DeviceConfigurationName <String>] [-DeviceName <String>] [-Id <String>]

   [-ManagedDeviceId <String>] [-PlatformType <PolicyPlatformType>]

   [-RestrictedApps <IMicrosoftGraphManagedDeviceReportedApp[]>] [-RestrictedAppsState <RestrictedAppsState>]

   [-UserId <String>] [-UserName <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementDeviceConfigurationRestrictedAppViolation

   -BodyParameter <IMicrosoftGraphRestrictedAppsViolation> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphRestrictedAppsViolation" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Violation of restricted apps configuration profile per device per user
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DeviceConfigurationId
  description: |+
    Device configuration profile unique identifier, must be Guid

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DeviceConfigurationName
  description: |+
    Device configuration profile name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DeviceName
  description: |+
    Device name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ManagedDeviceId
  description: |+
    Managed device unique identifier, must be Guid

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PolicyPlatformType" data-throw-if-not-resolved="False" />
  name: PlatformType
  description: |+
    Supported platform types for policies.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedDeviceReportedApp" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RestrictedApps
  description: |+
    List of violated restricted apps
    To construct, see NOTES section for RESTRICTEDAPPS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="RestrictedAppsState" data-throw-if-not-resolved="False" />
  name: RestrictedAppsState
  description: |+
    Restricted apps state

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserId
  description: |+
    User unique identifier, must be Guid

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserName
  description: |+
    User name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Administration.New-MgBetaDeviceManagementDeviceConfigurationRestrictedAppViolation
name: New-MgBetaDeviceManagementDeviceConfigurationRestrictedAppViolation
description: |-
  Create new navigation property to deviceConfigurationRestrictedAppsViolations for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement.Administration-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement.Administration
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement.administration/new-mgbetadevicemanagementdeviceconfigurationrestrictedappviolation
  schema: 2.0.0
