### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property deviceConfigurationsAllManagedDeviceCertificateStates in deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgDeviceManagementDeviceConfigurationManagedDeviceCertificateState](/powershell/module/Microsoft.Graph.DeviceManagement.Administration/Update-MgDeviceManagementDeviceConfigurationManagedDeviceCertificateState?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement.Administration
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphManagedAllDeviceCertificateState>`: managedAllDeviceCertificateState
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[CertificateExpirationDateTime <DateTime?>]`: Certificate expiry date
    - `[CertificateExtendedKeyUsages <String>]`: Enhanced Key Usage
    - `[CertificateIssuanceDateTime <DateTime?>]`: Issuance date
    - `[CertificateIssuerName <String>]`: Issuer
    - `[CertificateKeyUsages <Int32?>]`: Key Usage
    - `[CertificateRevokeStatus <CertificateRevocationStatus?>]`: Certificate Revocation Status.
    - `[CertificateRevokeStatusLastChangeDateTime <DateTime?>]`: The time the revoke status was last changed
    - `[CertificateSerialNumber <String>]`: Serial number
    - `[CertificateSubjectName <String>]`: Certificate subject name
    - `[CertificateThumbprint <String>]`: Thumbprint
    - `[ManagedDeviceDisplayName <String>]`: Device display name
    - `[UserPrincipalName <String>]`: User principal name

  `INPUTOBJECT <IDeviceManagementAdministrationIdentity>`: Identity Parameter
    - `[AuditEventId <String>]`: The unique identifier of auditEvent
    - `[CartToClassAssociationId <String>]`: The unique identifier of cartToClassAssociation
    - `[CloudPcAuditEventId <String>]`: The unique identifier of cloudPcAuditEvent
    - `[CloudPcBulkActionId <String>]`: The unique identifier of cloudPcBulkAction
    - `[CloudPcDeviceImageId <String>]`: The unique identifier of cloudPcDeviceImage
    - `[CloudPcExportJobId <String>]`: The unique identifier of cloudPcExportJob
    - `[CloudPcExternalPartnerSettingId <String>]`: The unique identifier of cloudPcExternalPartnerSetting
    - `[CloudPcGalleryImageId <String>]`: The unique identifier of cloudPcGalleryImage
    - `[CloudPcId <String>]`: The unique identifier of cloudPC
    - `[CloudPcOnPremisesConnectionId <String>]`: The unique identifier of cloudPcOnPremisesConnection
    - `[CloudPcProvisioningPolicyAssignmentId <String>]`: The unique identifier of cloudPcProvisioningPolicyAssignment
    - `[CloudPcProvisioningPolicyId <String>]`: The unique identifier of cloudPcProvisioningPolicy
    - `[CloudPcServicePlanId <String>]`: The unique identifier of cloudPcServicePlan
    - `[CloudPcSharedUseServicePlanId <String>]`: The unique identifier of cloudPcSharedUseServicePlan
    - `[CloudPcSnapshotId <String>]`: The unique identifier of cloudPcSnapshot
    - `[CloudPcSupportedRegionId <String>]`: The unique identifier of cloudPcSupportedRegion
    - `[CloudPcUserSettingAssignmentId <String>]`: The unique identifier of cloudPcUserSettingAssignment
    - `[CloudPcUserSettingId <String>]`: The unique identifier of cloudPcUserSetting
    - `[ComanagementEligibleDeviceId <String>]`: The unique identifier of comanagementEligibleDevice
    - `[ComplianceManagementPartnerId <String>]`: The unique identifier of complianceManagementPartner
    - `[DeviceAndAppManagementRoleAssignmentId <String>]`: The unique identifier of deviceAndAppManagementRoleAssignment
    - `[DeviceManagementDomainJoinConnectorId <String>]`: The unique identifier of deviceManagementDomainJoinConnector
    - `[DeviceManagementExchangeConnectorId <String>]`: The unique identifier of deviceManagementExchangeConnector
    - `[DeviceManagementExchangeOnPremisesPolicyId <String>]`: The unique identifier of deviceManagementExchangeOnPremisesPolicy
    - `[DeviceManagementPartnerId <String>]`: The unique identifier of deviceManagementPartner
    - `[GroupPolicyCategoryId <String>]`: The unique identifier of groupPolicyCategory
    - `[GroupPolicyCategoryId1 <String>]`: The unique identifier of groupPolicyCategory
    - `[GroupPolicyDefinitionFileId <String>]`: The unique identifier of groupPolicyDefinitionFile
    - `[GroupPolicyDefinitionId <String>]`: The unique identifier of groupPolicyDefinition
    - `[GroupPolicyMigrationReportId <String>]`: The unique identifier of groupPolicyMigrationReport
    - `[GroupPolicyObjectFileId <String>]`: The unique identifier of groupPolicyObjectFile
    - `[GroupPolicyOperationId <String>]`: The unique identifier of groupPolicyOperation
    - `[GroupPolicyPresentationId <String>]`: The unique identifier of groupPolicyPresentation
    - `[GroupPolicySettingMappingId <String>]`: The unique identifier of groupPolicySettingMapping
    - `[GroupPolicyUploadedDefinitionFileId <String>]`: The unique identifier of groupPolicyUploadedDefinitionFile
    - `[IntuneBrandingProfileAssignmentId <String>]`: The unique identifier of intuneBrandingProfileAssignment
    - `[IntuneBrandingProfileId <String>]`: The unique identifier of intuneBrandingProfile
    - `[IosUpdateDeviceStatusId <String>]`: The unique identifier of iosUpdateDeviceStatus
    - `[ManagedAllDeviceCertificateStateId <String>]`: The unique identifier of managedAllDeviceCertificateState
    - `[MobileThreatDefenseConnectorId <String>]`: The unique identifier of mobileThreatDefenseConnector
    - `[NdesConnectorId <String>]`: The unique identifier of ndesConnector
    - `[RemoteAssistancePartnerId <String>]`: The unique identifier of remoteAssistancePartner
    - `[ResourceOperationId <String>]`: The unique identifier of resourceOperation
    - `[RestrictedAppsViolationId <String>]`: The unique identifier of restrictedAppsViolation
    - `[RoleAssignmentId <String>]`: The unique identifier of roleAssignment
    - `[RoleDefinitionId <String>]`: The unique identifier of roleDefinition
    - `[RoleScopeTagAutoAssignmentId <String>]`: The unique identifier of roleScopeTagAutoAssignment
    - `[RoleScopeTagId <String>]`: The unique identifier of roleScopeTag
    - `[TelecomExpenseManagementPartnerId <String>]`: The unique identifier of telecomExpenseManagementPartner
    - `[TermsAndConditionsAcceptanceStatusId <String>]`: The unique identifier of termsAndConditionsAcceptanceStatus
    - `[TermsAndConditionsAssignmentId <String>]`: The unique identifier of termsAndConditionsAssignment
    - `[TermsAndConditionsGroupAssignmentId <String>]`: The unique identifier of termsAndConditionsGroupAssignment
    - `[TermsAndConditionsId <String>]`: The unique identifier of termsAndConditions
    - `[UnsupportedGroupPolicyExtensionId <String>]`: The unique identifier of unsupportedGroupPolicyExtension
    - `[UserId <String>]`: The unique identifier of user
    - `[UserPfxCertificateId <String>]`: The unique identifier of userPFXCertificate
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IDeviceManagementAdministrationIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphManagedAllDeviceCertificateState" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphManagedAllDeviceCertificateState" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgDeviceManagementDeviceConfigurationManagedDeviceCertificateState
  href: /powershell/module/Microsoft.Graph.DeviceManagement.Administration/Update-MgDeviceManagementDeviceConfigurationManagedDeviceCertificateState?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState

   -ManagedAllDeviceCertificateStateId <String> [-AdditionalProperties <Hashtable>]

   [-CertificateExpirationDateTime <DateTime>] [-CertificateExtendedKeyUsages <String>]

   [-CertificateIssuanceDateTime <DateTime>] [-CertificateIssuerName <String>] [-CertificateKeyUsages <Int32>]

   [-CertificateRevokeStatus <CertificateRevocationStatus>]

   [-CertificateRevokeStatusLastChangeDateTime <DateTime>] [-CertificateSerialNumber <String>]

   [-CertificateSubjectName <String>] [-CertificateThumbprint <String>] [-Id <String>]

   [-ManagedDeviceDisplayName <String>] [-UserPrincipalName <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState

   -ManagedAllDeviceCertificateStateId <String> -BodyParameter <IMicrosoftGraphManagedAllDeviceCertificateState>

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState

   -InputObject <IDeviceManagementAdministrationIdentity> [-AdditionalProperties <Hashtable>]

   [-CertificateExpirationDateTime <DateTime>] [-CertificateExtendedKeyUsages <String>]

   [-CertificateIssuanceDateTime <DateTime>] [-CertificateIssuerName <String>] [-CertificateKeyUsages <Int32>]

   [-CertificateRevokeStatus <CertificateRevocationStatus>]

   [-CertificateRevokeStatusLastChangeDateTime <DateTime>] [-CertificateSerialNumber <String>]

   [-CertificateSubjectName <String>] [-CertificateThumbprint <String>] [-Id <String>]

   [-ManagedDeviceDisplayName <String>] [-UserPrincipalName <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState

   -InputObject <IDeviceManagementAdministrationIdentity>

   -BodyParameter <IMicrosoftGraphManagedAllDeviceCertificateState> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedAllDeviceCertificateState" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    managedAllDeviceCertificateState
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CertificateExpirationDateTime
  description: |+
    Certificate expiry date

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateExtendedKeyUsages
  description: |+
    Enhanced Key Usage

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CertificateIssuanceDateTime
  description: |+
    Issuance date

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateIssuerName
  description: |+
    Issuer

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CertificateKeyUsages
  description: |+
    Key Usage

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CertificateRevocationStatus" data-throw-if-not-resolved="False" />
  name: CertificateRevokeStatus
  description: |+
    Certificate Revocation Status.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CertificateRevokeStatusLastChangeDateTime
  description: |+
    The time the revoke status was last changed

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateSerialNumber
  description: |+
    Serial number

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateSubjectName
  description: |+
    Certificate subject name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateThumbprint
  description: |+
    Thumbprint

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDeviceManagementAdministrationIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ManagedAllDeviceCertificateStateId
  isRequired: true
  description: |+
    The unique identifier of managedAllDeviceCertificateState

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ManagedDeviceDisplayName
  description: |+
    Device display name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserPrincipalName
  description: |+
    User principal name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Administration.Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState
name: Update-MgBetaDeviceManagementDeviceConfigurationManagedDeviceCertificateState
description: |-
  Update the navigation property deviceConfigurationsAllManagedDeviceCertificateStates in deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement.Administration-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement.Administration
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement.administration/update-mgbetadevicemanagementdeviceconfigurationmanageddevicecertificatestate
  schema: 2.0.0
