### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to userExperienceAnalyticsAppHealthApplicationPerformance for deviceManagement

  > [!NOTE]
  > To view the beta release of this cmdlet, view [New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance](/powershell/module/Microsoft.Graph.Beta.DeviceManagement/New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance?view=graph-powershell-beta)
module: Microsoft.Graph.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance>`: The user experience analytics application performance entity contains application performance details.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[ActiveDeviceCount <Int32?>]`: The health score of the application. Valid values 0 to 100. Supports: $filter, $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppCrashCount <Int32?>]`: The number of crashes for the application. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppDisplayName <String>]`: The friendly name of the application. Possible values are: Outlook, Excel. Supports: $select, $OrderBy. Read-only.
    - `[AppHangCount <Int32?>]`: The number of hangs for the application. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppHealthScore <Double?>]`: The health score of the application. Valid values 0 to 100. Supports: $filter, $select, $OrderBy. Read-only. Valid values -1.79769313486232E+308 to 1.79769313486232E+308
    - `[AppName <String>]`: The name of the application. Possible values are: outlook.exe, excel.exe. Supports: $select, $OrderBy. Read-only.
    - `[AppPublisher <String>]`: The publisher of the application. Supports: $select, $OrderBy. Read-only.
    - `[AppUsageDuration <Int32?>]`: The total usage time of the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[MeanTimeToFailureInMinutes <Int32?>]`: The mean time to failure for the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
  href: /powershell/module/Microsoft.Graph.Beta.DeviceManagement/New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance?view=graph-powershell-beta
syntaxes:
- >-
  New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance [-ActiveDeviceCount <Int32>]

   [-AdditionalProperties <Hashtable>] [-AppCrashCount <Int32>] [-AppDisplayName <String>]

   [-AppHangCount <Int32>] [-AppHealthScore <Double>] [-AppName <String>] [-AppPublisher <String>]

   [-AppUsageDuration <Int32>] [-Id <String>] [-MeanTimeToFailureInMinutes <Int32>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance

   -BodyParameter <IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ActiveDeviceCount
  description: |+
    The health score of the application.
    Valid values 0 to 100.
    Supports: $filter, $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppCrashCount
  description: |+
    The number of crashes for the application.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppDisplayName
  description: |+
    The friendly name of the application.
    Possible values are: Outlook, Excel.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppHangCount
  description: |+
    The number of hangs for the application.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" />
  name: AppHealthScore
  description: |+
    The health score of the application.
    Valid values 0 to 100.
    Supports: $filter, $select, $OrderBy.
    Read-only.
    Valid values -1.79769313486232E+308 to 1.79769313486232E+308

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppName
  description: |+
    The name of the application.
    Possible values are: outlook.exe, excel.exe.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppPublisher
  description: |+
    The publisher of the application.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppUsageDuration
  description: |+
    The total usage time of the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    The user experience analytics application performance entity contains application performance details.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MeanTimeToFailureInMinutes
  description: |+
    The mean time to failure for the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.DeviceManagement.New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
name: New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
description: |-
  Create new navigation property to userExperienceAnalyticsAppHealthApplicationPerformance for deviceManagement
metadata:
  external help file: Microsoft.Graph.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devicemanagement/new-mgdevicemanagementuserexperienceanalyticapphealthapplicationperformance
  schema: 2.0.0
