### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property userExperienceAnalyticsAppHealthApplicationPerformance in deviceManagement

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance](/powershell/module/Microsoft.Graph.Beta.DeviceManagement/Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance?view=graph-powershell-beta)
module: Microsoft.Graph.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance>`: The user experience analytics application performance entity contains application performance details.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[ActiveDeviceCount <Int32?>]`: The health score of the application. Valid values 0 to 100. Supports: $filter, $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppCrashCount <Int32?>]`: The number of crashes for the application. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppDisplayName <String>]`: The friendly name of the application. Possible values are: Outlook, Excel. Supports: $select, $OrderBy. Read-only.
    - `[AppHangCount <Int32?>]`: The number of hangs for the application. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppHealthScore <Double?>]`: The health score of the application. Valid values 0 to 100. Supports: $filter, $select, $OrderBy. Read-only. Valid values -1.79769313486232E+308 to 1.79769313486232E+308
    - `[AppName <String>]`: The name of the application. Possible values are: outlook.exe, excel.exe. Supports: $select, $OrderBy. Read-only.
    - `[AppPublisher <String>]`: The publisher of the application. Supports: $select, $OrderBy. Read-only.
    - `[AppUsageDuration <Int32?>]`: The total usage time of the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[MeanTimeToFailureInMinutes <Int32?>]`: The mean time to failure for the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647

  `INPUTOBJECT <IDeviceManagementIdentity>`: Identity Parameter
    - `[AppLogCollectionRequestId <String>]`: The unique identifier of appLogCollectionRequest
    - `[BrowserSharedCookieId <String>]`: The unique identifier of browserSharedCookie
    - `[BrowserSiteId <String>]`: The unique identifier of browserSite
    - `[BrowserSiteListId <String>]`: The unique identifier of browserSiteList
    - `[DetectedAppId <String>]`: The unique identifier of detectedApp
    - `[DeviceCategoryId <String>]`: The unique identifier of deviceCategory
    - `[DeviceComplianceActionItemId <String>]`: The unique identifier of deviceComplianceActionItem
    - `[DeviceComplianceDeviceStatusId <String>]`: The unique identifier of deviceComplianceDeviceStatus
    - `[DeviceCompliancePolicyAssignmentId <String>]`: The unique identifier of deviceCompliancePolicyAssignment
    - `[DeviceCompliancePolicyId <String>]`: The unique identifier of deviceCompliancePolicy
    - `[DeviceCompliancePolicySettingStateSummaryId <String>]`: The unique identifier of deviceCompliancePolicySettingStateSummary
    - `[DeviceCompliancePolicyStateId <String>]`: The unique identifier of deviceCompliancePolicyState
    - `[DeviceComplianceScheduledActionForRuleId <String>]`: The unique identifier of deviceComplianceScheduledActionForRule
    - `[DeviceComplianceSettingStateId <String>]`: The unique identifier of deviceComplianceSettingState
    - `[DeviceComplianceUserStatusId <String>]`: The unique identifier of deviceComplianceUserStatus
    - `[DeviceConfigurationAssignmentId <String>]`: The unique identifier of deviceConfigurationAssignment
    - `[DeviceConfigurationDeviceStatusId <String>]`: The unique identifier of deviceConfigurationDeviceStatus
    - `[DeviceConfigurationId <String>]`: The unique identifier of deviceConfiguration
    - `[DeviceConfigurationStateId <String>]`: The unique identifier of deviceConfigurationState
    - `[DeviceConfigurationUserStatusId <String>]`: The unique identifier of deviceConfigurationUserStatus
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DeviceManagementTroubleshootingEventId <String>]`: The unique identifier of deviceManagementTroubleshootingEvent
    - `[LocalizedNotificationMessageId <String>]`: The unique identifier of localizedNotificationMessage
    - `[MalwareStateForWindowsDeviceId <String>]`: The unique identifier of malwareStateForWindowsDevice
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[MobileAppTroubleshootingEventId <String>]`: The unique identifier of mobileAppTroubleshootingEvent
    - `[NotificationMessageTemplateId <String>]`: The unique identifier of notificationMessageTemplate
    - `[SettingStateDeviceSummaryId <String>]`: The unique identifier of settingStateDeviceSummary
    - `[UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetailsId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
    - `[UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId
    - `[UserExperienceAnalyticsAppHealthAppPerformanceByOSVersionId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthAppPerformanceByOSVersion
    - `[UserExperienceAnalyticsAppHealthApplicationPerformanceId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthApplicationPerformance
    - `[UserExperienceAnalyticsAppHealthDeviceModelPerformanceId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthDeviceModelPerformance
    - `[UserExperienceAnalyticsAppHealthDevicePerformanceDetailsId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthDevicePerformanceDetails
    - `[UserExperienceAnalyticsAppHealthDevicePerformanceId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthDevicePerformance
    - `[UserExperienceAnalyticsAppHealthOSVersionPerformanceId <String>]`: The unique identifier of userExperienceAnalyticsAppHealthOSVersionPerformance
    - `[UserExperienceAnalyticsBaselineId <String>]`: The unique identifier of userExperienceAnalyticsBaseline
    - `[UserExperienceAnalyticsCategoryId <String>]`: The unique identifier of userExperienceAnalyticsCategory
    - `[UserExperienceAnalyticsDevicePerformanceId <String>]`: The unique identifier of userExperienceAnalyticsDevicePerformance
    - `[UserExperienceAnalyticsDeviceScoresId <String>]`: The unique identifier of userExperienceAnalyticsDeviceScores
    - `[UserExperienceAnalyticsDeviceStartupHistoryId <String>]`: The unique identifier of userExperienceAnalyticsDeviceStartupHistory
    - `[UserExperienceAnalyticsDeviceStartupProcessId <String>]`: The unique identifier of userExperienceAnalyticsDeviceStartupProcess
    - `[UserExperienceAnalyticsMetricHistoryId <String>]`: The unique identifier of userExperienceAnalyticsMetricHistory
    - `[UserExperienceAnalyticsMetricId <String>]`: The unique identifier of userExperienceAnalyticsMetric
    - `[UserExperienceAnalyticsModelScoresId <String>]`: The unique identifier of userExperienceAnalyticsModelScores
    - `[UserExperienceAnalyticsScoreHistoryId <String>]`: The unique identifier of userExperienceAnalyticsScoreHistory
    - `[UserExperienceAnalyticsWorkFromAnywhereDeviceId <String>]`: The unique identifier of userExperienceAnalyticsWorkFromAnywhereDevice
    - `[UserExperienceAnalyticsWorkFromAnywhereMetricId <String>]`: The unique identifier of userExperienceAnalyticsWorkFromAnywhereMetric
    - `[UserExperienceAnalyticsWorkFromAnywhereModelPerformanceId <String>]`: The unique identifier of userExperienceAnalyticsWorkFromAnywhereModelPerformance
    - `[WindowsDeviceMalwareStateId <String>]`: The unique identifier of windowsDeviceMalwareState
    - `[WindowsInformationProtectionAppLearningSummaryId <String>]`: The unique identifier of windowsInformationProtectionAppLearningSummary
    - `[WindowsInformationProtectionNetworkLearningSummaryId <String>]`: The unique identifier of windowsInformationProtectionNetworkLearningSummary
    - `[WindowsMalwareInformationId <String>]`: The unique identifier of windowsMalwareInformation
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDeviceManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
  href: /powershell/module/Microsoft.Graph.Beta.DeviceManagement/Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance?view=graph-powershell-beta
syntaxes:
- >-
  Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance

   -UserExperienceAnalyticsAppHealthApplicationPerformanceId <String> [-ActiveDeviceCount <Int32>]

   [-AdditionalProperties <Hashtable>] [-AppCrashCount <Int32>] [-AppDisplayName <String>]

   [-AppHangCount <Int32>] [-AppHealthScore <Double>] [-AppName <String>] [-AppPublisher <String>]

   [-AppUsageDuration <Int32>] [-Id <String>] [-MeanTimeToFailureInMinutes <Int32>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance

   -UserExperienceAnalyticsAppHealthApplicationPerformanceId <String>

   -BodyParameter <IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance> [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance

   -InputObject <IDeviceManagementIdentity> [-ActiveDeviceCount <Int32>] [-AdditionalProperties <Hashtable>]

   [-AppCrashCount <Int32>] [-AppDisplayName <String>] [-AppHangCount <Int32>] [-AppHealthScore <Double>]

   [-AppName <String>] [-AppPublisher <String>] [-AppUsageDuration <Int32>] [-Id <String>]

   [-MeanTimeToFailureInMinutes <Int32>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance

   -InputObject <IDeviceManagementIdentity>

   -BodyParameter <IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ActiveDeviceCount
  description: |+
    The health score of the application.
    Valid values 0 to 100.
    Supports: $filter, $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppCrashCount
  description: |+
    The number of crashes for the application.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppDisplayName
  description: |+
    The friendly name of the application.
    Possible values are: Outlook, Excel.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppHangCount
  description: |+
    The number of hangs for the application.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Double" data-throw-if-not-resolved="False" />
  name: AppHealthScore
  description: |+
    The health score of the application.
    Valid values 0 to 100.
    Supports: $filter, $select, $OrderBy.
    Read-only.
    Valid values -1.79769313486232E+308 to 1.79769313486232E+308

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppName
  description: |+
    The name of the application.
    Possible values are: outlook.exe, excel.exe.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppPublisher
  description: |+
    The publisher of the application.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppUsageDuration
  description: |+
    The total usage time of the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphUserExperienceAnalyticsAppHealthApplicationPerformance" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    The user experience analytics application performance entity contains application performance details.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDeviceManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MeanTimeToFailureInMinutes
  description: |+
    The mean time to failure for the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserExperienceAnalyticsAppHealthApplicationPerformanceId
  isRequired: true
  description: |+
    The unique identifier of userExperienceAnalyticsAppHealthApplicationPerformance

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.DeviceManagement.Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
name: Update-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance
description: |-
  Update the navigation property userExperienceAnalyticsAppHealthApplicationPerformance in deviceManagement
metadata:
  external help file: Microsoft.Graph.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devicemanagement/update-mgdevicemanagementuserexperienceanalyticapphealthapplicationperformance
  schema: 2.0.0
