### YamlMime:PowershellCmdlet
summary: |-
  Get the number of the resource

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgWindowsUpdatesDeploymentAudienceMemberCount](/powershell/module/Microsoft.Graph.WindowsUpdates/Get-MgWindowsUpdatesDeploymentAudienceMemberCount?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.WindowsUpdates
notes: |-
  ALIASES

  Get-MgBetaWuDeploymentAudienceMemberCount

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `INPUTOBJECT <IWindowsUpdatesIdentity>`: Identity Parameter
    - `[CatalogEntryId <String>]`: The unique identifier of catalogEntry
    - `[ComplianceChangeId <String>]`: The unique identifier of complianceChange
    - `[DeploymentId <String>]`: The unique identifier of deployment
    - `[ResourceConnectionId <String>]`: The unique identifier of resourceConnection
    - `[UpdatableAssetId <String>]`: The unique identifier of updatableAsset
    - `[UpdatePolicyId <String>]`: The unique identifier of updatePolicy
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IWindowsUpdatesIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgWindowsUpdatesDeploymentAudienceMemberCount
  href: /powershell/module/Microsoft.Graph.WindowsUpdates/Get-MgWindowsUpdatesDeploymentAudienceMemberCount?view=graph-powershell-v1.0
syntaxes:
- >-
  Get-MgBetaWindowsUpdatesDeploymentAudienceMemberCount -DeploymentId <String> [-Filter <String>]

   [-Search <String>] [<CommonParameters>]
- >-
  Get-MgBetaWindowsUpdatesDeploymentAudienceMemberCount -InputObject <IWindowsUpdatesIdentity> [-Filter <String>]

   [-Search <String>] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DeploymentId
  isRequired: true
  description: |+
    The unique identifier of deployment

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Filter items by property values

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IWindowsUpdatesIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Search
  description: |+
    Search items by search phrases

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.WindowsUpdates.Get-MgBetaWindowsUpdatesDeploymentAudienceMemberCount
name: Get-MgBetaWindowsUpdatesDeploymentAudienceMemberCount
description: |-
  Get the number of the resource
metadata:
  external help file: Microsoft.Graph.Beta.WindowsUpdates-help.xml
  Module Name: Microsoft.Graph.Beta.WindowsUpdates
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.windowsupdates/get-mgbetawindowsupdatesdeploymentaudiencemembercount
  schema: 2.0.0
