### YamlMime:PowershellCmdlet
summary: |-
  Assign a connectorGroup to an application.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Set-MgApplicationConnectorGroupByRef](/powershell/module/Microsoft.Graph.Applications/Set-MgApplicationConnectorGroupByRef?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Applications
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IReferenceUpdate>`: .
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `OdataId <String>`: The entity reference URL of the resource. For example, https://graph.microsoft.com/v1.0/directoryObjects/{id}.
    - `[OdataType <String>]`: 

  `INPUTOBJECT <IApplicationsIdentity>`: Identity Parameter
    - `[AppManagementPolicyId <String>]`: The unique identifier of appManagementPolicy
    - `[AppRoleAssignmentId <String>]`: The unique identifier of appRoleAssignment
    - `[ApplicationId <String>]`: The unique identifier of application
    - `[ApplicationTemplateId <String>]`: The unique identifier of applicationTemplate
    - `[ClaimsMappingPolicyId <String>]`: The unique identifier of claimsMappingPolicy
    - `[ConnectorGroupId <String>]`: The unique identifier of connectorGroup
    - `[ConnectorId <String>]`: The unique identifier of connector
    - `[DelegatedPermissionClassificationId <String>]`: The unique identifier of delegatedPermissionClassification
    - `[DirectoryDefinitionId <String>]`: The unique identifier of directoryDefinition
    - `[DirectoryObjectId <String>]`: The unique identifier of directoryObject
    - `[EndpointId <String>]`: The unique identifier of endpoint
    - `[ExtensionPropertyId <String>]`: The unique identifier of extensionProperty
    - `[FederatedIdentityCredentialId <String>]`: The unique identifier of federatedIdentityCredential
    - `[GroupId <String>]`: The unique identifier of group
    - `[HomeRealmDiscoveryPolicyId <String>]`: The unique identifier of homeRealmDiscoveryPolicy
    - `[LicenseDetailsId <String>]`: The unique identifier of licenseDetails
    - `[OAuth2PermissionGrantId <String>]`: The unique identifier of oAuth2PermissionGrant
    - `[OnPremisesAgentGroupId <String>]`: The unique identifier of onPremisesAgentGroup
    - `[OnPremisesAgentGroupId1 <String>]`: The unique identifier of onPremisesAgentGroup
    - `[OnPremisesAgentId <String>]`: The unique identifier of onPremisesAgent
    - `[OnPremisesPublishingProfileId <String>]`: The unique identifier of onPremisesPublishingProfile
    - `[PublishedResourceId <String>]`: The unique identifier of publishedResource
    - `[ServicePrincipalId <String>]`: The unique identifier of servicePrincipal
    - `[SynchronizationJobId <String>]`: The unique identifier of synchronizationJob
    - `[SynchronizationTemplateId <String>]`: The unique identifier of synchronizationTemplate
    - `[TokenIssuancePolicyId <String>]`: The unique identifier of tokenIssuancePolicy
    - `[TokenLifetimePolicyId <String>]`: The unique identifier of tokenLifetimePolicy
    - `[UserId <String>]`: The unique identifier of user
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IApplicationsIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IReferenceUpdate" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-MgApplicationConnectorGroupByRef
  href: /powershell/module/Microsoft.Graph.Applications/Set-MgApplicationConnectorGroupByRef?view=graph-powershell-v1.0
syntaxes:
- >-
  Set-MgBetaApplicationConnectorGroupByRef -ApplicationId <String> -OdataId <String>

   [-AdditionalProperties <Hashtable>] [-OdataType <String>] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-MgBetaApplicationConnectorGroupByRef -ApplicationId <String> -BodyParameter <IReferenceUpdate> [-PassThru]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-MgBetaApplicationConnectorGroupByRef -InputObject <IApplicationsIdentity> -OdataId <String>

   [-AdditionalProperties <Hashtable>] [-OdataType <String>] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-MgBetaApplicationConnectorGroupByRef -InputObject <IApplicationsIdentity> -BodyParameter <IReferenceUpdate>

   [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Using the Set-MgBetaApplicationConnectorGroupByRef Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Applications
    $params = @{
    	"@odata.id" = "https://graph.microsoft.com/onPremisesPublishingProfiles/applicationproxy/connectorGroups/{id}"
    }
    Set-MgBetaApplicationConnectorGroupByRef -ApplicationId $applicationId -BodyParameter $params
  description: |-
    This example shows how to use the Set-MgBetaApplicationConnectorGroupByRef Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  isRequired: true
  description: |+
    The unique identifier of application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IReferenceUpdate" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    .
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IApplicationsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OdataId
  isRequired: true
  description: |+
    The entity reference URL of the resource.
    For example, https://graph.microsoft.com/v1.0/directoryObjects/{id}.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OdataType
  description: |+
    .

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns true when the command succeeds

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Applications.Set-MgBetaApplicationConnectorGroupByRef
name: Set-MgBetaApplicationConnectorGroupByRef
description: |-
  Assign a connectorGroup to an application.
metadata:
  external help file: Microsoft.Graph.Beta.Applications-help.xml
  Module Name: Microsoft.Graph.Beta.Applications
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.applications/set-mgbetaapplicationconnectorgroupbyref
  schema: 2.0.0
