### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to userStatuses for deviceAppManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceAppManagementMobileAppConfigurationUserStatus](/powershell/module/Microsoft.Graph.Devices.CorporateManagement/New-MgDeviceAppManagementMobileAppConfigurationUserStatus?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Devices.CorporateManagement
notes: |-
  ALIASES

  New-MgBetaDeviceAppMgtMobileAppConfigurationUserStatus

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus>`: Contains properties, inherited properties and actions for an MDM mobile app configuration status for a user.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[DevicesCount <Int32?>]`: Devices count for that user.
    - `[LastReportedDateTime <DateTime?>]`: Last modified date time of the policy report.
    - `[Status <String>]`: complianceStatus
    - `[UserDisplayName <String>]`: User name of the DevicePolicyStatus.
    - `[UserPrincipalName <String>]`: UserPrincipalName.

  `INPUTOBJECT <IDevicesCorporateManagementIdentity>`: Identity Parameter
    - `[AndroidManagedAppProtectionId <String>]`: The unique identifier of androidManagedAppProtection
    - `[AppLogCollectionRequestId <String>]`: The unique identifier of appLogCollectionRequest
    - `[AssignmentFilterEvaluationStatusDetailsId <String>]`: The unique identifier of assignmentFilterEvaluationStatusDetails
    - `[BundleId <String>]`: Usage: bundleId='{bundleId}'
    - `[DefaultManagedAppProtectionId <String>]`: The unique identifier of defaultManagedAppProtection
    - `[DetectedAppId <String>]`: The unique identifier of detectedApp
    - `[DeviceAppManagementTaskId <String>]`: The unique identifier of deviceAppManagementTask
    - `[DeviceCompliancePolicyStateId <String>]`: The unique identifier of deviceCompliancePolicyState
    - `[DeviceConfigurationStateId <String>]`: The unique identifier of deviceConfigurationState
    - `[DeviceEnrollmentConfigurationId <String>]`: The unique identifier of deviceEnrollmentConfiguration
    - `[DeviceId <String>]`: Property in multi-part unique identifier of deviceHealthScriptPolicyState
    - `[DeviceInstallStateId <String>]`: The unique identifier of deviceInstallState
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DeviceManagementConfigurationSettingDefinitionId <String>]`: The unique identifier of deviceManagementConfigurationSettingDefinition
    - `[DeviceManagementConfigurationSettingId <String>]`: The unique identifier of deviceManagementConfigurationSetting
    - `[DeviceManagementTroubleshootingEventId <String>]`: The unique identifier of deviceManagementTroubleshootingEvent
    - `[EnrollmentConfigurationAssignmentId <String>]`: The unique identifier of enrollmentConfigurationAssignment
    - `[EnterpriseCodeSigningCertificateId <String>]`: The unique identifier of enterpriseCodeSigningCertificate
    - `[Id <String>]`: Property in multi-part unique identifier of deviceHealthScriptPolicyState
    - `[IosLobAppProvisioningConfigurationAssignmentId <String>]`: The unique identifier of iosLobAppProvisioningConfigurationAssignment
    - `[IosLobAppProvisioningConfigurationId <String>]`: The unique identifier of iosLobAppProvisioningConfiguration
    - `[IosManagedAppProtectionId <String>]`: The unique identifier of iosManagedAppProtection
    - `[ManagedAppOperationId <String>]`: The unique identifier of managedAppOperation
    - `[ManagedAppPolicyId <String>]`: The unique identifier of managedAppPolicy
    - `[ManagedAppRegistrationId <String>]`: The unique identifier of managedAppRegistration
    - `[ManagedAppStatusId <String>]`: The unique identifier of managedAppStatus
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[ManagedDeviceMobileAppConfigurationAssignmentId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationAssignment
    - `[ManagedDeviceMobileAppConfigurationDeviceStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationDeviceStatus
    - `[ManagedDeviceMobileAppConfigurationId <String>]`: The unique identifier of managedDeviceMobileAppConfiguration
    - `[ManagedDeviceMobileAppConfigurationStateId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationState
    - `[ManagedDeviceMobileAppConfigurationUserStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationUserStatus
    - `[ManagedEBookAssignmentId <String>]`: The unique identifier of managedEBookAssignment
    - `[ManagedEBookCategoryId <String>]`: The unique identifier of managedEBookCategory
    - `[ManagedEBookId <String>]`: The unique identifier of managedEBook
    - `[ManagedMobileAppId <String>]`: The unique identifier of managedMobileApp
    - `[MdmWindowsInformationProtectionPolicyId <String>]`: The unique identifier of mdmWindowsInformationProtectionPolicy
    - `[MobileAppAssignmentId <String>]`: The unique identifier of mobileAppAssignment
    - `[MobileAppCategoryId <String>]`: The unique identifier of mobileAppCategory
    - `[MobileAppId <String>]`: The unique identifier of mobileApp
    - `[MobileAppIntentAndStateId <String>]`: The unique identifier of mobileAppIntentAndState
    - `[MobileAppProvisioningConfigGroupAssignmentId <String>]`: The unique identifier of mobileAppProvisioningConfigGroupAssignment
    - `[MobileAppRelationshipId <String>]`: The unique identifier of mobileAppRelationship
    - `[MobileAppTroubleshootingEventId <String>]`: The unique identifier of mobileAppTroubleshootingEvent
    - `[PolicyId <String>]`: Property in multi-part unique identifier of deviceHealthScriptPolicyState
    - `[PolicySetAssignmentId <String>]`: The unique identifier of policySetAssignment
    - `[PolicySetId <String>]`: The unique identifier of policySet
    - `[PolicySetItemId <String>]`: The unique identifier of policySetItem
    - `[SecurityBaselineSettingStateId <String>]`: The unique identifier of securityBaselineSettingState
    - `[SecurityBaselineStateId <String>]`: The unique identifier of securityBaselineState
    - `[TargetedManagedAppConfigurationId <String>]`: The unique identifier of targetedManagedAppConfiguration
    - `[TargetedManagedAppPolicyAssignmentId <String>]`: The unique identifier of targetedManagedAppPolicyAssignment
    - `[UserId <String>]`: The unique identifier of user
    - `[UserInstallStateSummaryId <String>]`: The unique identifier of userInstallStateSummary
    - `[VppTokenId <String>]`: The unique identifier of vppToken
    - `[WindowsDefenderApplicationControlSupplementalPolicyAssignmentId <String>]`: The unique identifier of windowsDefenderApplicationControlSupplementalPolicyAssignment
    - `[WindowsDefenderApplicationControlSupplementalPolicyDeploymentStatusId <String>]`: The unique identifier of windowsDefenderApplicationControlSupplementalPolicyDeploymentStatus
    - `[WindowsDefenderApplicationControlSupplementalPolicyId <String>]`: The unique identifier of windowsDefenderApplicationControlSupplementalPolicy
    - `[WindowsDeviceMalwareStateId <String>]`: The unique identifier of windowsDeviceMalwareState
    - `[WindowsInformationProtectionAppLockerFileId <String>]`: The unique identifier of windowsInformationProtectionAppLockerFile
    - `[WindowsInformationProtectionDeviceRegistrationId <String>]`: The unique identifier of windowsInformationProtectionDeviceRegistration
    - `[WindowsInformationProtectionPolicyId <String>]`: The unique identifier of windowsInformationProtectionPolicy
    - `[WindowsInformationProtectionWipeActionId <String>]`: The unique identifier of windowsInformationProtectionWipeAction
    - `[WindowsManagedAppProtectionId <String>]`: The unique identifier of windowsManagedAppProtection
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceAppManagementMobileAppConfigurationUserStatus
  href: /powershell/module/Microsoft.Graph.Devices.CorporateManagement/New-MgDeviceAppManagementMobileAppConfigurationUserStatus?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus -ManagedDeviceMobileAppConfigurationId <String>

   [-AdditionalProperties <Hashtable>] [-DevicesCount <Int32>] [-Id <String>] [-LastReportedDateTime <DateTime>]

   [-Status <String>] [-UserDisplayName <String>] [-UserPrincipalName <String>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus -ManagedDeviceMobileAppConfigurationId <String>

   -BodyParameter <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus> [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus

   -InputObject <IDevicesCorporateManagementIdentity> [-AdditionalProperties <Hashtable>] [-DevicesCount <Int32>]

   [-Id <String>] [-LastReportedDateTime <DateTime>] [-Status <String>] [-UserDisplayName <String>]

   [-UserPrincipalName <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus

   -InputObject <IDevicesCorporateManagementIdentity>

   -BodyParameter <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedDeviceMobileAppConfigurationUserStatus" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Contains properties, inherited properties and actions for an MDM mobile app configuration status for a user.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DevicesCount
  description: |+
    Devices count for that user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastReportedDateTime
  description: |+
    Last modified date time of the policy report.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ManagedDeviceMobileAppConfigurationId
  isRequired: true
  description: |+
    The unique identifier of managedDeviceMobileAppConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Status
  description: |+
    complianceStatus

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserDisplayName
  description: |+
    User name of the DevicePolicyStatus.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserPrincipalName
  description: |+
    UserPrincipalName.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Devices.CorporateManagement.New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus
name: New-MgBetaDeviceAppManagementMobileAppConfigurationUserStatus
description: |-
  Create new navigation property to userStatuses for deviceAppManagement
metadata:
  external help file: Microsoft.Graph.Beta.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Beta.Devices.CorporateManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devices.corporatemanagement/new-mgbetadeviceappmanagementmobileappconfigurationuserstatus
  schema: 2.0.0
