### YamlMime:PowershellCmdlet
summary: |-
  List the tokenLifetimePolicy objects that are assigned to an application.
  Only one object is returned in the collection because only one tokenLifetimePolicy can be assigned to an application.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaApplicationTokenLifetimePolicy](/powershell/module/Microsoft.Graph.Beta.Applications/Get-MgBetaApplicationTokenLifetimePolicy?view=graph-powershell-beta)
module: Microsoft.Graph.Applications
notes: |-
  ALIASES
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphTokenLifetimePolicy" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaApplicationTokenLifetimePolicy
  href: /powershell/module/Microsoft.Graph.Beta.Applications/Get-MgBetaApplicationTokenLifetimePolicy?view=graph-powershell-beta
syntaxes:
- >-
  Get-MgApplicationTokenLifetimePolicy -ApplicationId <String> [-ExpandProperty <String[]>] [-Filter <String>]

   [-Property <String[]>] [-Search <String>] [-Skip <Int32>] [-Sort <String[]>] [-Top <Int32>]

   [-PageSize <Int32>] [-All] [-CountVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Using the Get-MgApplicationTokenLifetimePolicy Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Applications
    Get-MgApplicationTokenLifetimePolicy -ApplicationId $applicationId
  description: |-
    This example shows how to use the Get-MgApplicationTokenLifetimePolicy Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    List all pages.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationId
  isRequired: true
  description: |+
    The unique identifier of application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CountVariable
  description: |+
    Specifies a count of the total number of items in a collection.
    By default, this variable will be set in the global scope.

  defaultValue: None
  position: Named
  aliases: CV
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Filter items by property values

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PageSize
  description: |+
    Sets the page size of results.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Search
  description: |+
    Search items by search phrases

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Skip
  description: |+
    Skip the first n items

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Sort
  description: |+
    Order items by property values

  defaultValue: None
  position: Named
  aliases: OrderBy
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Show only the first n items

  defaultValue: None
  position: Named
  aliases: Limit
  parameterValueGroup: ""
uid: Microsoft.Graph.Applications.Get-MgApplicationTokenLifetimePolicy
name: Get-MgApplicationTokenLifetimePolicy
description: |-
  List the tokenLifetimePolicy objects that are assigned to an application.
  Only one object is returned in the collection because only one tokenLifetimePolicy can be assigned to an application.
metadata:
  external help file: Microsoft.Graph.Applications-help.xml
  Module Name: Microsoft.Graph.Applications
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.applications/get-mgapplicationtokenlifetimepolicy
  schema: 2.0.0
