### YamlMime:PowershellCmdlet
summary: |-
  Get the number of the resource

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaApplicationCount](/powershell/module/Microsoft.Graph.Beta.Applications/Get-MgBetaApplicationCount?view=graph-powershell-beta)
module: Microsoft.Graph.Applications
notes: |-
  ALIASES
outputs:
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaApplicationCount
  href: /powershell/module/Microsoft.Graph.Beta.Applications/Get-MgBetaApplicationCount?view=graph-powershell-beta
syntaxes:
- Get-MgApplicationCount [-Filter <String>] [-Search <String>] -ConsistencyLevel <String> [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConsistencyLevel
  isRequired: true
  description: |+
    Indicates the requested consistency level.
    Documentation URL: https://docs.microsoft.com/graph/aad-advanced-queries

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Filter items by property values

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Search
  description: |+
    Search items by search phrases

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Applications.Get-MgApplicationCount
name: Get-MgApplicationCount
description: |-
  Get the number of the resource
metadata:
  external help file: Microsoft.Graph.Applications-help.xml
  Module Name: Microsoft.Graph.Applications
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.applications/get-mgapplicationcount
  schema: 2.0.0
