### YamlMime:PowershellCmdlet
summary: |-
  Represents an abstract type that contains resources for attack simulation and training reports.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaReportSecurity](/powershell/module/Microsoft.Graph.Beta.Reports/Get-MgBetaReportSecurity?view=graph-powershell-beta)
module: Microsoft.Graph.Reports
notes: |-
  ALIASES
outputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaReportSecurity
  href: /powershell/module/Microsoft.Graph.Beta.Reports/Get-MgBetaReportSecurity?view=graph-powershell-beta
syntaxes:
- Get-MgReportSecurity [-ExpandProperty <String[]>] [-Property <String[]>] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
uid: Microsoft.Graph.Reports.Get-MgReportSecurity
name: Get-MgReportSecurity
description: |-
  Represents an abstract type that contains resources for attack simulation and training reports.
metadata:
  external help file: Microsoft.Graph.Reports-help.xml
  Module Name: Microsoft.Graph.Reports
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.reports/get-mgreportsecurity
  schema: 2.0.0
