### YamlMime:PowershellCmdlet
summary: |-
  Invoke function availableProviderTypes

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Invoke-MgBetaAvailableDirectoryFederationConfigurationProviderType](/powershell/module/Microsoft.Graph.Beta.Identity.DirectoryManagement/Invoke-MgBetaAvailableDirectoryFederationConfigurationProviderType?view=graph-powershell-beta)
module: Microsoft.Graph.Identity.DirectoryManagement
notes: |-
  ALIASES
outputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Invoke-MgBetaAvailableDirectoryFederationConfigurationProviderType
  href: /powershell/module/Microsoft.Graph.Beta.Identity.DirectoryManagement/Invoke-MgBetaAvailableDirectoryFederationConfigurationProviderType?view=graph-powershell-beta
syntaxes:
- >-
  Invoke-MgAvailableDirectoryFederationConfigurationProviderType [-Count] [-Filter <String>] [-Search <String>]

   [-Skip <Int32>] [-Top <Int32>] [<CommonParameters>]
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Count
  description: |+
    Include count of items

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Filter items by property values

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Search
  description: |+
    Search items by search phrases

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Skip
  description: |+
    Skip the first n items

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Show only the first n items

  defaultValue: None
  position: Named
  aliases: Limit
  parameterValueGroup: ""
uid: Microsoft.Graph.Identity.DirectoryManagement.Invoke-MgAvailableDirectoryFederationConfigurationProviderType
name: Invoke-MgAvailableDirectoryFederationConfigurationProviderType
description: |-
  Invoke function availableProviderTypes
metadata:
  external help file: Microsoft.Graph.Identity.DirectoryManagement-help.xml
  Module Name: Microsoft.Graph.Identity.DirectoryManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.identity.directorymanagement/invoke-mgavailabledirectoryfederationconfigurationprovidertype
  schema: 2.0.0
