### YamlMime:PowershellCmdlet
summary: |-
  Deployment profile currently assigned to the Windows autopilot device.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile](/powershell/module/Microsoft.Graph.DeviceManagement.Enrolment/Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile?view=graph-powershell-v1.0)
module: Microsoft.Graph.DeviceManagement.Enrolment
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  INPUTOBJECT `<IDeviceManagementEnrolmentIdentity>`: Identity Parameter
    - `[AndroidDeviceOwnerEnrollmentProfileId <String>]`: The unique identifier of androidDeviceOwnerEnrollmentProfile
    - `[AndroidForWorkEnrollmentProfileId <String>]`: The unique identifier of androidForWorkEnrollmentProfile
    - `[AppScopeId <String>]`: The unique identifier of appScope
    - `[AppleEnrollmentProfileAssignmentId <String>]`: The unique identifier of appleEnrollmentProfileAssignment
    - `[AppleUserInitiatedEnrollmentProfileId <String>]`: The unique identifier of appleUserInitiatedEnrollmentProfile
    - `[ApprovalId <String>]`: The unique identifier of approval
    - `[ApprovalStepId <String>]`: The unique identifier of approvalStep
    - `[DepOnboardingSettingId <String>]`: The unique identifier of depOnboardingSetting
    - `[DeviceEnrollmentConfigurationId <String>]`: The unique identifier of deviceEnrollmentConfiguration
    - `[DeviceManagementAutopilotEventId <String>]`: The unique identifier of deviceManagementAutopilotEvent
    - `[DeviceManagementAutopilotPolicyStatusDetailId <String>]`: The unique identifier of deviceManagementAutopilotPolicyStatusDetail
    - `[DirectoryObjectId <String>]`: The unique identifier of directoryObject
    - `[EnrollmentConfigurationAssignmentId <String>]`: The unique identifier of enrollmentConfigurationAssignment
    - `[EnrollmentProfileId <String>]`: The unique identifier of enrollmentProfile
    - `[ImportedAppleDeviceIdentityId <String>]`: The unique identifier of importedAppleDeviceIdentity
    - `[ImportedDeviceIdentityId <String>]`: The unique identifier of importedDeviceIdentity
    - `[ImportedWindowsAutopilotDeviceIdentityId <String>]`: The unique identifier of importedWindowsAutopilotDeviceIdentity
    - `[On <String>]`: Usage: on='{on}'
    - `[UnifiedRbacResourceActionId <String>]`: The unique identifier of unifiedRbacResourceAction
    - `[UnifiedRbacResourceNamespaceId <String>]`: The unique identifier of unifiedRbacResourceNamespace
    - `[UnifiedRoleAssignmentId <String>]`: The unique identifier of unifiedRoleAssignment
    - `[UnifiedRoleAssignmentMultipleId <String>]`: The unique identifier of unifiedRoleAssignmentMultiple
    - `[UnifiedRoleAssignmentScheduleId <String>]`: The unique identifier of unifiedRoleAssignmentSchedule
    - `[UnifiedRoleAssignmentScheduleInstanceId <String>]`: The unique identifier of unifiedRoleAssignmentScheduleInstance
    - `[UnifiedRoleAssignmentScheduleRequestId <String>]`: The unique identifier of unifiedRoleAssignmentScheduleRequest
    - `[UnifiedRoleDefinitionId <String>]`: The unique identifier of unifiedRoleDefinition
    - `[UnifiedRoleDefinitionId1 <String>]`: The unique identifier of unifiedRoleDefinition
    - `[UnifiedRoleEligibilityScheduleId <String>]`: The unique identifier of unifiedRoleEligibilitySchedule
    - `[UnifiedRoleEligibilityScheduleInstanceId <String>]`: The unique identifier of unifiedRoleEligibilityScheduleInstance
    - `[UnifiedRoleEligibilityScheduleRequestId <String>]`: The unique identifier of unifiedRoleEligibilityScheduleRequest
    - `[WindowsAutopilotDeploymentProfileAssignmentId <String>]`: The unique identifier of windowsAutopilotDeploymentProfileAssignment
    - `[WindowsAutopilotDeploymentProfileId <String>]`: The unique identifier of windowsAutopilotDeploymentProfile
    - `[WindowsAutopilotDeviceIdentityId <String>]`: The unique identifier of windowsAutopilotDeviceIdentity
    - `[WindowsFeatureUpdateProfileAssignmentId <String>]`: The unique identifier of windowsFeatureUpdateProfileAssignment
    - `[WindowsFeatureUpdateProfileId <String>]`: The unique identifier of windowsFeatureUpdateProfile
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDeviceManagementEnrolmentIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphWindowsAutopilotDeploymentProfile" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile
  href: /powershell/module/Microsoft.Graph.DeviceManagement.Enrolment/Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile?view=graph-powershell-v1.0
syntaxes:
- >-
  Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile -WindowsAutopilotDeviceIdentityId <String>

   [-ExpandProperty <String[]>] [-Property <String[]>] [<CommonParameters>]
- >-
  Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile

   -InputObject <IDeviceManagementEnrolmentIdentity> [-ExpandProperty <String[]>] [-Property <String[]>]

   [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="IDeviceManagementEnrolmentIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, please use Get-Help -Online and see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: WindowsAutopilotDeviceIdentityId
  isRequired: true
  description: |+
    The unique identifier of windowsAutopilotDeviceIdentity

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.DeviceManagement.Enrolment.Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile
name: Get-MgDeviceManagementWindowAutopilotDeviceIdentityDeploymentProfile
description: |-
  Deployment profile currently assigned to the Windows autopilot device.
metadata:
  external help file: Microsoft.Graph.DeviceManagement.Enrolment-help.xml
  Module Name: Microsoft.Graph.DeviceManagement.Enrolment
  online version: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.enrolment/get-mgdevicemanagementwindowautopilotdeviceidentitydeploymentprofile
  schema: 2.0.0
