### YamlMime:PowershellCmdlet
summary: |-
  Metadata for the device configuration user activity report

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgReportDeviceConfigurationUserActivity](/powershell/module/Microsoft.Graph.Reports/Get-MgReportDeviceConfigurationUserActivity?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Reports
notes: |-
  ALIASES
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgReportDeviceConfigurationUserActivity
  href: /powershell/module/Microsoft.Graph.Reports/Get-MgReportDeviceConfigurationUserActivity?view=graph-powershell-v1.0
syntaxes:
- Get-MgBetaReportDeviceConfigurationUserActivity -OutFile <String> [-PassThru] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OutFile
  isRequired: true
  description: |+
    Path to write output file to

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns true when the command succeeds

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Reports.Get-MgBetaReportDeviceConfigurationUserActivity
name: Get-MgBetaReportDeviceConfigurationUserActivity
description: |-
  Metadata for the device configuration user activity report
metadata:
  external help file: Microsoft.Graph.Beta.Reports-help.xml
  Module Name: Microsoft.Graph.Beta.Reports
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.reports/get-mgbetareportdeviceconfigurationuseractivity
  schema: 2.0.0
