### YamlMime:PowershellCmdlet
summary: |-
  Retrieve the properties and relationships of a shiftPreferences object by ID.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgUserSettingShiftPreference](/powershell/module/Microsoft.Graph.Users/Get-MgUserSettingShiftPreference?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Users
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `INPUTOBJECT <IUsersIdentity>`: Identity Parameter
    - `[AttachmentBaseId <String>]`: The unique identifier of attachmentBase
    - `[AttachmentId <String>]`: The unique identifier of attachment
    - `[AttachmentSessionId <String>]`: The unique identifier of attachmentSession
    - `[ChecklistItemId <String>]`: The unique identifier of checklistItem
    - `[DirectoryObjectId <String>]`: The unique identifier of directoryObject
    - `[ExtensionId <String>]`: The unique identifier of extension
    - `[LicenseDetailsId <String>]`: The unique identifier of licenseDetails
    - `[LinkedResourceId <String>]`: The unique identifier of linkedResource
    - `[NotificationId <String>]`: The unique identifier of notification
    - `[OAuth2PermissionGrantId <String>]`: The unique identifier of oAuth2PermissionGrant
    - `[OutlookCategoryId <String>]`: The unique identifier of outlookCategory
    - `[OutlookTaskFolderId <String>]`: The unique identifier of outlookTaskFolder
    - `[OutlookTaskGroupId <String>]`: The unique identifier of outlookTaskGroup
    - `[OutlookTaskId <String>]`: The unique identifier of outlookTask
    - `[ProfilePhotoId <String>]`: The unique identifier of profilePhoto
    - `[ServicePrincipalId <String>]`: The unique identifier of servicePrincipal
    - `[SharedInsightId <String>]`: The unique identifier of sharedInsight
    - `[TodoTaskId <String>]`: The unique identifier of todoTask
    - `[TodoTaskListId <String>]`: The unique identifier of todoTaskList
    - `[TrendingId <String>]`: The unique identifier of trending
    - `[UsedInsightId <String>]`: The unique identifier of usedInsight
    - `[UserId <String>]`: The unique identifier of user
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IUsersIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphShiftPreferences" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgUserSettingShiftPreference
  href: /powershell/module/Microsoft.Graph.Users/Get-MgUserSettingShiftPreference?view=graph-powershell-v1.0
syntaxes:
- >-
  Get-MgBetaUserSettingShiftPreference -UserId <String> [-ExpandProperty <String[]>] [-Property <String[]>]

   [<CommonParameters>]
- >-
  Get-MgBetaUserSettingShiftPreference -InputObject <IUsersIdentity> [-ExpandProperty <String[]>]

   [-Property <String[]>] [<CommonParameters>]
examples:
- title: 'Example 1: Code snippet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Users

    Get-MgBetaUserSettingShiftPreference -UserId $userId
  description: |-
    This example shows how to use the Get-MgBetaUserSettingShiftPreference Cmdlet.

    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="IUsersIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserId
  isRequired: true
  description: |+
    The unique identifier of user

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Users.Get-MgBetaUserSettingShiftPreference
name: Get-MgBetaUserSettingShiftPreference
description: |-
  Retrieve the properties and relationships of a shiftPreferences object by ID.
metadata:
  external help file: Microsoft.Graph.Beta.Users-help.xml
  Module Name: Microsoft.Graph.Beta.Users
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.users/get-mgbetausersettingshiftpreference
  schema: 2.0.0
