### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to federationConfigurations for directory

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDirectoryFederationConfiguration](/powershell/module/Microsoft.Graph.Identity.DirectoryManagement/New-MgDirectoryFederationConfiguration?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Identity.DirectoryManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphIdentityProviderBase>`: identityProviderBase
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[DisplayName <String>]`: The display name of the identity provider.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphIdentityProviderBase" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphIdentityProviderBase" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDirectoryFederationConfiguration
  href: /powershell/module/Microsoft.Graph.Identity.DirectoryManagement/New-MgDirectoryFederationConfiguration?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDirectoryFederationConfiguration [-AdditionalProperties <Hashtable>] [-DisplayName <String>]

   [-Id <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDirectoryFederationConfiguration -BodyParameter <IMicrosoftGraphIdentityProviderBase> [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Using the New-MgBetaDirectoryFederationConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.DirectoryManagement
    $params = @{
    	"@odata.type" = "microsoft.graph.samlOrWsFedExternalDomainFederation"
    	IssuerUri = "https://contoso.com/issuerUri"
    	DisplayName = "contoso display name"
    	MetadataExchangeUri = "https://contoso.com/metadataExchangeUri"
    	PassiveSignInUri = "https://contoso.com/signin"
    	PreferredAuthenticationProtocol = "wsFed"
    	Domains = @(
    		@{
    			"@odata.type" = "microsoft.graph.externalDomainName"
    			Id = "contoso.com"
    		}
    	)
    	SigningCertificate = "MIIDADCCAeigAwIBAgIQEX41y8r6"
    }
    New-MgBetaDirectoryFederationConfiguration -BodyParameter $params
  description: |-
    This example shows how to use the New-MgBetaDirectoryFederationConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphIdentityProviderBase" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    identityProviderBase
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    The display name of the identity provider.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Identity.DirectoryManagement.New-MgBetaDirectoryFederationConfiguration
name: New-MgBetaDirectoryFederationConfiguration
description: |-
  Create new navigation property to federationConfigurations for directory
metadata:
  external help file: Microsoft.Graph.Beta.Identity.DirectoryManagement-help.xml
  Module Name: Microsoft.Graph.Beta.Identity.DirectoryManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.identity.directorymanagement/new-mgbetadirectoryfederationconfiguration
  schema: 2.0.0
