### YamlMime:PowershellCmdlet
summary: |-
  Update the settings in a microsoftApplicationDataAccessSettings object that specify access from Microsoft applications to Microsoft 365 user data in an organization.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgOrganizationSettingMicrosoftApplicationDataAccess](/powershell/module/Microsoft.Graph.Identity.DirectoryManagement/Update-MgOrganizationSettingMicrosoftApplicationDataAccess?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Identity.DirectoryManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphMicrosoftApplicationDataAccessSettings>`: microsoftApplicationDataAccessSettings
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[DisabledForGroup <String>]`: The ID of an Azure Active Directory (Azure AD) security group for which the members are allowed to access Microsoft 365 data using only Microsoft 365 apps, but not other Microsoft apps such as Edge.  This is only applicable if isEnabledForAllMicrosoftApplications is set to true.
    - `[IsEnabledForAllMicrosoftApplications <Boolean?>]`: When set to true, all users in the organization can access in a Microsoft app any Microsoft 365 data that the user has been authorized to access. The Microsoft app can be a Microsoft 365 app (for example, Excel, Outlook) or non-Microsoft 365 app (for example, Edge). The default is true.  It is possible to disable this access for a subset of users in an Azure AD security group, by specifying the group in the disabledForGroup property.  When set to false, all users can access authorized Microsoft 365 data only in a Microsoft 365 app.

  `INPUTOBJECT <IIdentityDirectoryManagementIdentity>`: Identity Parameter
    - `[AdministrativeUnitId <String>]`: The unique identifier of administrativeUnit
    - `[AllowedValueId <String>]`: The unique identifier of allowedValue
    - `[AttributeSetId <String>]`: The unique identifier of attributeSet
    - `[CertificateAuthorityAsEntityId <String>]`: The unique identifier of certificateAuthorityAsEntity
    - `[CertificateBasedApplicationConfigurationId <String>]`: The unique identifier of certificateBasedApplicationConfiguration
    - `[CommandId <String>]`: The unique identifier of command
    - `[CompanySubscriptionId <String>]`: The unique identifier of companySubscription
    - `[ContractId <String>]`: The unique identifier of contract
    - `[CustomSecurityAttributeDefinitionId <String>]`: The unique identifier of customSecurityAttributeDefinition
    - `[DeviceId <String>]`: The unique identifier of device
    - `[DirectoryObjectId <String>]`: The unique identifier of directoryObject
    - `[DirectoryRoleId <String>]`: The unique identifier of directoryRole
    - `[DirectoryRoleTemplateId <String>]`: The unique identifier of directoryRoleTemplate
    - `[DirectorySettingId <String>]`: The unique identifier of directorySetting
    - `[DirectorySettingTemplateId <String>]`: The unique identifier of directorySettingTemplate
    - `[DomainDnsRecordId <String>]`: The unique identifier of domainDnsRecord
    - `[DomainId <String>]`: The unique identifier of domain
    - `[ExtensionId <String>]`: The unique identifier of extension
    - `[FeatureRolloutPolicyId <String>]`: The unique identifier of featureRolloutPolicy
    - `[IdentityProviderBaseId <String>]`: The unique identifier of identityProviderBase
    - `[ImpactedResourceId <String>]`: The unique identifier of impactedResource
    - `[InboundSharedUserProfileUserId <String>]`: The unique identifier of inboundSharedUserProfile
    - `[InternalDomainFederationId <String>]`: The unique identifier of internalDomainFederation
    - `[ManagedTenantAlertId <String>]`: The unique identifier of managedTenantAlert
    - `[ManagementActionId <String>]`: The unique identifier of managementAction
    - `[OnPremisesDirectorySynchronizationId <String>]`: The unique identifier of onPremisesDirectorySynchronization
    - `[OrgContactId <String>]`: The unique identifier of orgContact
    - `[OrganizationId <String>]`: The unique identifier of organization
    - `[OrganizationalBrandingLocalizationId <String>]`: The unique identifier of organizationalBrandingLocalization
    - `[OutboundSharedUserProfileUserId <String>]`: The unique identifier of outboundSharedUserProfile
    - `[ProfileCardPropertyId <String>]`: The unique identifier of profileCardProperty
    - `[RecommendationId <String>]`: The unique identifier of recommendation
    - `[ScopedRoleMembershipId <String>]`: The unique identifier of scopedRoleMembership
    - `[SharedEmailDomainId <String>]`: The unique identifier of sharedEmailDomain
    - `[SharedEmailDomainInvitationId <String>]`: The unique identifier of sharedEmailDomainInvitation
    - `[SubscribedSkuId <String>]`: The unique identifier of subscribedSku
    - `[TenantId <String>]`: The unique identifier of tenant
    - `[TenantReferenceTenantId <String>]`: The unique identifier of tenantReference
    - `[TenantTagId <String>]`: The unique identifier of tenantTag
    - `[UsageRightId <String>]`: The unique identifier of usageRight
    - `[UserId <String>]`: The unique identifier of user
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IIdentityDirectoryManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphMicrosoftApplicationDataAccessSettings" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphMicrosoftApplicationDataAccessSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgOrganizationSettingMicrosoftApplicationDataAccess
  href: /powershell/module/Microsoft.Graph.Identity.DirectoryManagement/Update-MgOrganizationSettingMicrosoftApplicationDataAccess?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess -OrganizationId <String>

   [-AdditionalProperties <Hashtable>] [-DisabledForGroup <String>] [-Id <String>]

   [-IsEnabledForAllMicrosoftApplications] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess -OrganizationId <String>

   -BodyParameter <IMicrosoftGraphMicrosoftApplicationDataAccessSettings> [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess

   -InputObject <IIdentityDirectoryManagementIdentity> [-AdditionalProperties <Hashtable>]

   [-DisabledForGroup <String>] [-Id <String>] [-IsEnabledForAllMicrosoftApplications] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess

   -InputObject <IIdentityDirectoryManagementIdentity>

   -BodyParameter <IMicrosoftGraphMicrosoftApplicationDataAccessSettings> [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Using the Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.DirectoryManagement
    $params = @{
    	DisabledForGroup = "edbfe4fb-ec70-4300-928f-dbb2ae86c981"
    }
    Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess -OrganizationId $organizationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphMicrosoftApplicationDataAccessSettings" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    microsoftApplicationDataAccessSettings
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisabledForGroup
  description: |+
    The ID of an Azure Active Directory (Azure AD) security group for which the members are allowed to access Microsoft 365 data using only Microsoft 365 apps, but not other Microsoft apps such as Edge.
    This is only applicable if isEnabledForAllMicrosoftApplications is set to true.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IIdentityDirectoryManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsEnabledForAllMicrosoftApplications
  description: |+
    When set to true, all users in the organization can access in a Microsoft app any Microsoft 365 data that the user has been authorized to access.
    The Microsoft app can be a Microsoft 365 app (for example, Excel, Outlook) or non-Microsoft 365 app (for example, Edge).
    The default is true.
    It is possible to disable this access for a subset of users in an Azure AD security group, by specifying the group in the disabledForGroup property.
    When set to false, all users can access authorized Microsoft 365 data only in a Microsoft 365 app.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OrganizationId
  isRequired: true
  description: |+
    The unique identifier of organization

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Identity.DirectoryManagement.Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess
name: Update-MgBetaOrganizationSettingMicrosoftApplicationDataAccess
description: |-
  Update the settings in a microsoftApplicationDataAccessSettings object that specify access from Microsoft applications to Microsoft 365 user data in an organization.
metadata:
  external help file: Microsoft.Graph.Beta.Identity.DirectoryManagement-help.xml
  Module Name: Microsoft.Graph.Beta.Identity.DirectoryManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.identity.directorymanagement/update-mgbetaorganizationsettingmicrosoftapplicationdataaccess
  schema: 2.0.0
