### YamlMime:PowershellCmdlet
summary: |-
  Compute the information protection label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key/value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Test-MgInformationProtectionPolicyLabelApplication](/powershell/module/Microsoft.Graph.Identity.SignIns/Test-MgInformationProtectionPolicyLabelApplication?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Identity.SignIns
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IPaths1Aushj1InformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>`: .
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[ContentInfo <IMicrosoftGraphContentInfo>]`: contentInfo
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Format <String>]`: contentFormat
      - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
      - `[Metadata <IMicrosoftGraphKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key/value pairs, where the key is the MSIP_Label_GUID_PropName.
        - `[Name <String>]`: Name for this key-value pair
        - `[Value <String>]`: Value for this key-value pair
      - `[State <String>]`: contentState
    - `[LabelingOptions <IMicrosoftGraphLabelingOptions>]`: labelingOptions
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[AssignmentMethod <String>]`: assignmentMethod
      - `[DowngradeJustification <IMicrosoftGraphDowngradeJustification>]`: downgradeJustification
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
        - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
      - `[ExtendedProperties <IMicrosoftGraphKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard MIP labeled metadata format as part of the label information.
      - `[LabelId <String>]`: The GUID of the label that should be applied to the information.

  `CONTENTINFO <IMicrosoftGraphContentInfo>`: contentInfo
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Format <String>]`: contentFormat
    - `[Identifier <String>]`: Identifier used for Azure Information Protection Analytics.
    - `[Metadata <IMicrosoftGraphKeyValuePair[]>]`: Existing Microsoft Purview Information Protection metadata is passed as key/value pairs, where the key is the MSIP_Label_GUID_PropName.
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[State <String>]`: contentState

  `LABELINGOPTIONS <IMicrosoftGraphLabelingOptions>`: labelingOptions
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[AssignmentMethod <String>]`: assignmentMethod
    - `[DowngradeJustification <IMicrosoftGraphDowngradeJustification>]`: downgradeJustification
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[IsDowngradeJustified <Boolean?>]`: Indicates whether the downgrade is or is not justified.
      - `[JustificationMessage <String>]`: Message that indicates why a downgrade is justified. The message will appear in administrative logs.
    - `[ExtendedProperties <IMicrosoftGraphKeyValuePair[]>]`: Extended properties will be parsed and returned in the standard MIP labeled metadata format as part of the label information.
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[LabelId <String>]`: The GUID of the label that should be applied to the information.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IPaths1Aushj1InformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphInformationProtectionAction" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Test-MgInformationProtectionPolicyLabelApplication
  href: /powershell/module/Microsoft.Graph.Identity.SignIns/Test-MgInformationProtectionPolicyLabelApplication?view=graph-powershell-v1.0
syntaxes:
- >-
  Test-MgBetaInformationProtectionPolicyLabelApplication [-AdditionalProperties <Hashtable>]

   [-ContentInfo <IMicrosoftGraphContentInfo>] [-LabelingOptions <IMicrosoftGraphLabelingOptions>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Test-MgBetaInformationProtectionPolicyLabelApplication

   -BodyParameter <IPaths1Aushj1InformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema>

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Using the Test-MgBetaInformationProtectionPolicyLabelApplication Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	ContentInfo = @{
    		"@odata.type" = "#microsoft.graph.contentInfo"
    		"Format@odata.type" = "#microsoft.graph.contentFormat"
    		Format = "default"
    		Identifier = $null
    		"State@odata.type" = "#microsoft.graph.contentState"
    		State = "rest"
    		"Metadata@odata.type" = "#Collection(microsoft.graph.keyValuePair)"
    		Metadata = @(
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_Enabled"
    				Value = "True"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_Method"
    				Value = "Standard"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_SetDate"
    				Value = "1/1/0001 12:00:00 AM"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_SiteId"
    				Value = "cfa4cf1d-a337-4481-aa99-19d8f3d63f7c"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_Name"
    				Value = "General"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_ContentBits"
    				Value = "0"
    			}
    			@{
    				"@odata.type" = "#microsoft.graph.keyValuePair"
    				Name = "MSIP_Label_722a5300-ac39-4c9a-88e3-f54c46676417_ActionId"
    				Value = "00000000-0000-0000-0000-000000000000"
    			}
    		)
    	}
    	LabelingOptions = @{
    		"@odata.type" = "#microsoft.graph.labelingOptions"
    		"AssignmentMethod@odata.type" = "#microsoft.graph.assignmentMethod"
    		AssignmentMethod = "standard"
    		"LabelId@odata.type" = "#Guid"
    		LabelId = "97309856-9c28-4ac6-9382-5f8bc20c457b"
    		DowngradeJustification = $null
    		"ExtendedProperties@odata.type" = "#Collection(microsoft.graph.keyValuePair)"
    		ExtendedProperties = @(
    		)
    	}
    }
    Test-MgBetaInformationProtectionPolicyLabelApplication -BodyParameter $params
  description: |-
    This example shows how to use the Test-MgBetaInformationProtectionPolicyLabelApplication Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IPaths1Aushj1InformationprotectionPolicyLabelsMicrosoftGraphEvaluateapplicationPostRequestbodyContentApplicationJsonSchema" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    .
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphContentInfo" data-throw-if-not-resolved="False" />
  name: ContentInfo
  description: |+
    contentInfo
    To construct, see NOTES section for CONTENTINFO properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphLabelingOptions" data-throw-if-not-resolved="False" />
  name: LabelingOptions
  description: |+
    labelingOptions
    To construct, see NOTES section for LABELINGOPTIONS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Identity.SignIns.Test-MgBetaInformationProtectionPolicyLabelApplication
name: Test-MgBetaInformationProtectionPolicyLabelApplication
description: |-
  Compute the information protection label that should be applied and return the set of actions that must be taken to correctly label the information.
  This API is useful when a label should be set manually or explicitly by a user or service, rather than automatically based on file contents.
  Given contentInfo, which includes existing content metadata key/value pairs, and labelingOptions as an input, the API returns an informationProtectionAction object that contains one of more of the following:
metadata:
  external help file: Microsoft.Graph.Beta.Identity.SignIns-help.xml
  Module Name: Microsoft.Graph.Beta.Identity.SignIns
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.identity.signins/test-mgbetainformationprotectionpolicylabelapplication
  schema: 2.0.0
