### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property authenticationMethodConfigurations in policies

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration](/powershell/module/Microsoft.Graph.Identity.SignIns/Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Identity.SignIns
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphAuthenticationMethodConfiguration>`: authenticationMethodConfiguration
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[ExcludeTargets <IMicrosoftGraphExcludeTarget[]>]`: Groups of users that are excluded from a policy.
      - `[Id <String>]`: The object identifier of an Azure AD group.
      - `[TargetType <String>]`: authenticationMethodTargetType
    - `[State <String>]`: authenticationMethodState

  `EXCLUDETARGETS <IMicrosoftGraphExcludeTarget[]>`: Groups of users that are excluded from a policy.
    - `[Id <String>]`: The object identifier of an Azure AD group.
    - `[TargetType <String>]`: authenticationMethodTargetType

  `INPUTOBJECT <IIdentitySignInsIdentity>`: Identity Parameter
    - `[ActivityBasedTimeoutPolicyId <String>]`: The unique identifier of activityBasedTimeoutPolicy
    - `[AppManagementPolicyId <String>]`: The unique identifier of appManagementPolicy
    - `[AuthenticationCombinationConfigurationId <String>]`: The unique identifier of authenticationCombinationConfiguration
    - `[AuthenticationContextClassReferenceId <String>]`: The unique identifier of authenticationContextClassReference
    - `[AuthenticationEventListenerId <String>]`: The unique identifier of authenticationEventListener
    - `[AuthenticationEventsFlowId <String>]`: The unique identifier of authenticationEventsFlow
    - `[AuthenticationMethodConfigurationId <String>]`: The unique identifier of authenticationMethodConfiguration
    - `[AuthenticationMethodId <String>]`: The unique identifier of authenticationMethod
    - `[AuthenticationMethodModeDetailId <String>]`: The unique identifier of authenticationMethodModeDetail
    - `[AuthenticationMethodModes <String[]>]`: Usage: authenticationMethodModes={authenticationMethodModes}
    - `[AuthenticationStrengthPolicyId <String>]`: The unique identifier of authenticationStrengthPolicy
    - `[AuthorizationPolicyId <String>]`: The unique identifier of authorizationPolicy
    - `[B2CIdentityUserFlowId <String>]`: The unique identifier of b2cIdentityUserFlow
    - `[B2XIdentityUserFlowId <String>]`: The unique identifier of b2xIdentityUserFlow
    - `[BitlockerRecoveryKeyId <String>]`: The unique identifier of bitlockerRecoveryKey
    - `[CertificateBasedAuthConfigurationId <String>]`: The unique identifier of certificateBasedAuthConfiguration
    - `[ClaimsMappingPolicyId <String>]`: The unique identifier of claimsMappingPolicy
    - `[ConditionalAccessPolicyId <String>]`: The unique identifier of conditionalAccessPolicy
    - `[ConditionalAccessTemplateId <String>]`: The unique identifier of conditionalAccessTemplate
    - `[CrossTenantAccessPolicyConfigurationPartnerTenantId <String>]`: The unique identifier of crossTenantAccessPolicyConfigurationPartner
    - `[CustomAuthenticationExtensionId <String>]`: The unique identifier of customAuthenticationExtension
    - `[DataLossPreventionPolicyId <String>]`: The unique identifier of dataLossPreventionPolicy
    - `[DataPolicyOperationId <String>]`: The unique identifier of dataPolicyOperation
    - `[DefaultUserRoleOverrideId <String>]`: The unique identifier of defaultUserRoleOverride
    - `[DirectoryObjectId <String>]`: The unique identifier of directoryObject
    - `[EmailAuthenticationMethodId <String>]`: The unique identifier of emailAuthenticationMethod
    - `[FeatureRolloutPolicyId <String>]`: The unique identifier of featureRolloutPolicy
    - `[Fido2AuthenticationMethodId <String>]`: The unique identifier of fido2AuthenticationMethod
    - `[GroupId <String>]`: The unique identifier of group
    - `[HomeRealmDiscoveryPolicyId <String>]`: The unique identifier of homeRealmDiscoveryPolicy
    - `[IdentityApiConnectorId <String>]`: The unique identifier of identityApiConnector
    - `[IdentityProviderBaseId <String>]`: The unique identifier of identityProviderBase
    - `[IdentityProviderId <String>]`: The unique identifier of identityProvider
    - `[IdentityUserFlowAttributeAssignmentId <String>]`: The unique identifier of identityUserFlowAttributeAssignment
    - `[IdentityUserFlowAttributeId <String>]`: The unique identifier of identityUserFlowAttribute
    - `[IdentityUserFlowId <String>]`: The unique identifier of identityUserFlow
    - `[InformationProtectionLabelId <String>]`: The unique identifier of informationProtectionLabel
    - `[InvitationId <String>]`: The unique identifier of invitation
    - `[LongRunningOperationId <String>]`: The unique identifier of longRunningOperation
    - `[MicrosoftAuthenticatorAuthenticationMethodId <String>]`: The unique identifier of microsoftAuthenticatorAuthenticationMethod
    - `[MobilityManagementPolicyId <String>]`: The unique identifier of mobilityManagementPolicy
    - `[NamedLocationId <String>]`: The unique identifier of namedLocation
    - `[OAuth2PermissionGrantId <String>]`: The unique identifier of oAuth2PermissionGrant
    - `[OrganizationId <String>]`: The unique identifier of organization
    - `[PasswordAuthenticationMethodId <String>]`: The unique identifier of passwordAuthenticationMethod
    - `[PasswordlessMicrosoftAuthenticatorAuthenticationMethodId <String>]`: The unique identifier of passwordlessMicrosoftAuthenticatorAuthenticationMethod
    - `[PermissionGrantConditionSetId <String>]`: The unique identifier of permissionGrantConditionSet
    - `[PermissionGrantPolicyId <String>]`: The unique identifier of permissionGrantPolicy
    - `[PhoneAuthenticationMethodId <String>]`: The unique identifier of phoneAuthenticationMethod
    - `[RiskDetectionId <String>]`: The unique identifier of riskDetection
    - `[RiskyServicePrincipalHistoryItemId <String>]`: The unique identifier of riskyServicePrincipalHistoryItem
    - `[RiskyServicePrincipalId <String>]`: The unique identifier of riskyServicePrincipal
    - `[RiskyUserHistoryItemId <String>]`: The unique identifier of riskyUserHistoryItem
    - `[RiskyUserId <String>]`: The unique identifier of riskyUser
    - `[SensitivityLabelId <String>]`: The unique identifier of sensitivityLabel
    - `[SensitivityLabelId1 <String>]`: The unique identifier of sensitivityLabel
    - `[ServicePrincipalCreationConditionSetId <String>]`: The unique identifier of servicePrincipalCreationConditionSet
    - `[ServicePrincipalCreationPolicyId <String>]`: The unique identifier of servicePrincipalCreationPolicy
    - `[ServicePrincipalRiskDetectionId <String>]`: The unique identifier of servicePrincipalRiskDetection
    - `[SoftwareOathAuthenticationMethodId <String>]`: The unique identifier of softwareOathAuthenticationMethod
    - `[TemporaryAccessPassAuthenticationMethodId <String>]`: The unique identifier of temporaryAccessPassAuthenticationMethod
    - `[ThreatAssessmentRequestId <String>]`: The unique identifier of threatAssessmentRequest
    - `[ThreatAssessmentResultId <String>]`: The unique identifier of threatAssessmentResult
    - `[TokenIssuancePolicyId <String>]`: The unique identifier of tokenIssuancePolicy
    - `[TokenLifetimePolicyId <String>]`: The unique identifier of tokenLifetimePolicy
    - `[TrustFrameworkKeySetId <String>]`: The unique identifier of trustFrameworkKeySet
    - `[TrustFrameworkPolicyId <String>]`: The unique identifier of trustFrameworkPolicy
    - `[UnifiedRoleManagementPolicyAssignmentId <String>]`: The unique identifier of unifiedRoleManagementPolicyAssignment
    - `[UnifiedRoleManagementPolicyId <String>]`: The unique identifier of unifiedRoleManagementPolicy
    - `[UnifiedRoleManagementPolicyRuleId <String>]`: The unique identifier of unifiedRoleManagementPolicyRule
    - `[UserFlowLanguageConfigurationId <String>]`: The unique identifier of userFlowLanguageConfiguration
    - `[UserFlowLanguagePageId <String>]`: The unique identifier of userFlowLanguagePage
    - `[UserId <String>]`: The unique identifier of user
    - `[WindowsHelloForBusinessAuthenticationMethodId <String>]`: The unique identifier of windowsHelloForBusinessAuthenticationMethod
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IIdentitySignInsIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphAuthenticationMethodConfiguration" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphAuthenticationMethodConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration
  href: /powershell/module/Microsoft.Graph.Identity.SignIns/Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration

   -AuthenticationMethodConfigurationId <String> [-AdditionalProperties <Hashtable>]

   [-ExcludeTargets <IMicrosoftGraphExcludeTarget[]>] [-Id <String>] [-State <String>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration

   -AuthenticationMethodConfigurationId <String>

   -BodyParameter <IMicrosoftGraphAuthenticationMethodConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration

   -InputObject <IIdentitySignInsIdentity> [-AdditionalProperties <Hashtable>]

   [-ExcludeTargets <IMicrosoftGraphExcludeTarget[]>] [-Id <String>] [-State <String>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration

   -InputObject <IIdentitySignInsIdentity> -BodyParameter <IMicrosoftGraphAuthenticationMethodConfiguration>

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.emailAuthenticationMethodConfiguration"
    	AllowExternalIdToUseEmailOtp = "disabled"
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 2: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.fido2AuthenticationMethodConfiguration"
    	State = "enabled"
    	IsAttestationEnforced = "true"
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 3: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration"
    	State = "enabled"
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 4: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.passwordlessMicrosoftAuthenticatorAuthenticationMethodConfiguration"
    	State = "enabled"
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 5: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.smsAuthenticationMethodConfiguration"
    	Id = "Sms"
    	State = "enabled"
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 6: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration"
    	IsUsableOnce = $true
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
- title: 'Example 7: Using the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet'
  code: |-
    Import-Module Microsoft.Graph.Beta.Identity.SignIns
    $params = @{
    	"@odata.type" = "#microsoft.graph.x509CertificateAuthenticationMethodConfiguration"
    	Id = "X509Certificate"
    	State = "enabled"
    	CertificateUserBindings = @(
    	)
    	IncludeTargets = @(
    	)
    }
    Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration -AuthenticationMethodConfigurationId $authenticationMethodConfigurationId -BodyParameter $params
  description: |-
    This example shows how to use the Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration Cmdlet.
    To learn about permissions for this resource, see the [permissions reference](/graph/permissions-reference).
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AuthenticationMethodConfigurationId
  isRequired: true
  description: |+
    The unique identifier of authenticationMethodConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphAuthenticationMethodConfiguration" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    authenticationMethodConfiguration
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphExcludeTarget" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExcludeTargets
  description: |+
    Groups of users that are excluded from a policy.
    To construct, see NOTES section for EXCLUDETARGETS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IIdentitySignInsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    authenticationMethodState

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Identity.SignIns.Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration
name: Update-MgBetaPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration
description: |-
  Update the navigation property authenticationMethodConfigurations in policies
metadata:
  external help file: Microsoft.Graph.Beta.Identity.SignIns-help.xml
  Module Name: Microsoft.Graph.Beta.Identity.SignIns
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.identity.signins/update-mgbetapolicyauthenticationmethodpolicyauthenticationmethodconfiguration
  schema: 2.0.0
