### YamlMime:PowershellCmdlet
summary: |-
  Update the properties of a plannerPlanConfigurationLocalization object.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgBusinessScenarioPlannerPlanConfigurationLocalization](/powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerPlanConfigurationLocalization?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Bookings
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphPlannerPlanConfigurationLocalization>`: plannerPlanConfigurationLocalization
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>]`: Localized names for configured buckets in the plan configuration.
      - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.
      - `[Name <String>]`: Name of the bucket.
    - `[LanguageTag <String>]`: The language code associated with the localized names in this object.
    - `[PlanTitle <String>]`: Localized title of the plan.

  `BUCKETS <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>`: Localized names for configured buckets in the plan configuration.
    - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.
    - `[Name <String>]`: Name of the bucket.

  `INPUTOBJECT <IBookingsIdentity>`: Identity Parameter
    - `[AttendanceRecordId <String>]`: The unique identifier of attendanceRecord
    - `[BookingAppointmentId <String>]`: The unique identifier of bookingAppointment
    - `[BookingBusinessId <String>]`: The unique identifier of bookingBusiness
    - `[BookingCurrencyId <String>]`: The unique identifier of bookingCurrency
    - `[BookingCustomQuestionId <String>]`: The unique identifier of bookingCustomQuestion
    - `[BookingCustomerId <String>]`: The unique identifier of bookingCustomer
    - `[BookingServiceId <String>]`: The unique identifier of bookingService
    - `[BookingStaffMemberId <String>]`: The unique identifier of bookingStaffMember
    - `[BusinessScenarioId <String>]`: The unique identifier of businessScenario
    - `[BusinessScenarioTaskId <String>]`: The unique identifier of businessScenarioTask
    - `[CallRecordingId <String>]`: The unique identifier of callRecording
    - `[CallTranscriptId <String>]`: The unique identifier of callTranscript
    - `[MeetingAttendanceReportId <String>]`: The unique identifier of meetingAttendanceReport
    - `[MeetingRegistrantBaseId <String>]`: The unique identifier of meetingRegistrantBase
    - `[MeetingRegistrationQuestionId <String>]`: The unique identifier of meetingRegistrationQuestion
    - `[PlannerPlanConfigurationLocalizationId <String>]`: The unique identifier of plannerPlanConfigurationLocalization
    - `[VirtualEventId <String>]`: The unique identifier of virtualEvent
    - `[VirtualEventPresenterId <String>]`: The unique identifier of virtualEventPresenter
    - `[VirtualEventSessionId <String>]`: The unique identifier of virtualEventSession
    - `[VirtualEventWebinarId <String>]`: The unique identifier of virtualEventWebinar
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IBookingsIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerPlanConfigurationLocalization" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerPlanConfigurationLocalization" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBusinessScenarioPlannerPlanConfigurationLocalization
  href: /powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerPlanConfigurationLocalization?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization -BusinessScenarioId <String>

   -PlannerPlanConfigurationLocalizationId <String> [-AdditionalProperties <Hashtable>]

   [-Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>] [-Id <String>]

   [-LanguageTag <String>] [-PlanTitle <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization -BusinessScenarioId <String>

   -PlannerPlanConfigurationLocalizationId <String>

   -BodyParameter <IMicrosoftGraphPlannerPlanConfigurationLocalization> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization -InputObject <IBookingsIdentity>

   [-AdditionalProperties <Hashtable>] [-Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>]

   [-Id <String>] [-LanguageTag <String>] [-PlanTitle <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization -InputObject <IBookingsIdentity>

   -BodyParameter <IMicrosoftGraphPlannerPlanConfigurationLocalization> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerPlanConfigurationLocalization" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    plannerPlanConfigurationLocalization
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerPlanConfigurationBucketLocalization" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Buckets
  description: |+
    Localized names for configured buckets in the plan configuration.
    To construct, see NOTES section for BUCKETS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BusinessScenarioId
  isRequired: true
  description: |+
    The unique identifier of businessScenario

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IBookingsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LanguageTag
  description: |+
    The language code associated with the localized names in this object.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PlannerPlanConfigurationLocalizationId
  isRequired: true
  description: |+
    The unique identifier of plannerPlanConfigurationLocalization

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PlanTitle
  description: |+
    Localized title of the plan.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Bookings.Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization
name: Update-MgBetaBusinessScenarioPlannerPlanConfigurationLocalization
description: |-
  Update the properties of a plannerPlanConfigurationLocalization object.
metadata:
  external help file: Microsoft.Graph.Beta.Bookings-help.xml
  Module Name: Microsoft.Graph.Beta.Bookings
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.bookings/update-mgbetabusinessscenarioplannerplanconfigurationlocalization
  schema: 2.0.0
