### YamlMime:PowershellCmdlet
summary: |-
  Update the properties of a plannerPlanConfiguration object for a businessScenario.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgBusinessScenarioPlannerPlanConfiguration](/powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerPlanConfiguration?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Bookings
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphPlannerPlanConfiguration>`: plannerPlanConfiguration
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketDefinition[]>]`: List the buckets that should be created in the plan.
      - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.
    - `[CreatedBy <IMicrosoftGraphIdentitySet>]`: identitySet
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Application <IMicrosoftGraphIdentity>]`: identity
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
        - `[Id <String>]`: Unique identifier for the identity.
      - `[Device <IMicrosoftGraphIdentity>]`: identity
      - `[User <IMicrosoftGraphIdentity>]`: identity
    - `[CreatedDateTime <DateTime?>]`: The date and time when the plan configuration was created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.
    - `[DefaultLanguage <String>]`: The language code for the default language to be used for the names of the objects created for the plan.
    - `[LastModifiedBy <IMicrosoftGraphIdentitySet>]`: identitySet
    - `[LastModifiedDateTime <DateTime?>]`: The date and time when the plan configuration was last modified. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.
    - `[Localizations <IMicrosoftGraphPlannerPlanConfigurationLocalization[]>]`: Localized names for the plan configuration.
      - `[Id <String>]`: The unique identifier for an entity. Read-only.
      - `[Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>]`: Localized names for configured buckets in the plan configuration.
        - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.
        - `[Name <String>]`: Name of the bucket.
      - `[LanguageTag <String>]`: The language code associated with the localized names in this object.
      - `[PlanTitle <String>]`: Localized title of the plan.

  `BUCKETS <IMicrosoftGraphPlannerPlanConfigurationBucketDefinition[]>`: List the buckets that should be created in the plan.
    - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.

  `CREATEDBY <IMicrosoftGraphIdentitySet>`: identitySet
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Application <IMicrosoftGraphIdentity>]`: identity
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
      - `[Id <String>]`: Unique identifier for the identity.
    - `[Device <IMicrosoftGraphIdentity>]`: identity
    - `[User <IMicrosoftGraphIdentity>]`: identity

  `INPUTOBJECT <IBookingsIdentity>`: Identity Parameter
    - `[AttendanceRecordId <String>]`: The unique identifier of attendanceRecord
    - `[BookingAppointmentId <String>]`: The unique identifier of bookingAppointment
    - `[BookingBusinessId <String>]`: The unique identifier of bookingBusiness
    - `[BookingCurrencyId <String>]`: The unique identifier of bookingCurrency
    - `[BookingCustomQuestionId <String>]`: The unique identifier of bookingCustomQuestion
    - `[BookingCustomerId <String>]`: The unique identifier of bookingCustomer
    - `[BookingServiceId <String>]`: The unique identifier of bookingService
    - `[BookingStaffMemberId <String>]`: The unique identifier of bookingStaffMember
    - `[BusinessScenarioId <String>]`: The unique identifier of businessScenario
    - `[BusinessScenarioTaskId <String>]`: The unique identifier of businessScenarioTask
    - `[CallRecordingId <String>]`: The unique identifier of callRecording
    - `[CallTranscriptId <String>]`: The unique identifier of callTranscript
    - `[MeetingAttendanceReportId <String>]`: The unique identifier of meetingAttendanceReport
    - `[MeetingRegistrantBaseId <String>]`: The unique identifier of meetingRegistrantBase
    - `[MeetingRegistrationQuestionId <String>]`: The unique identifier of meetingRegistrationQuestion
    - `[PlannerPlanConfigurationLocalizationId <String>]`: The unique identifier of plannerPlanConfigurationLocalization
    - `[VirtualEventId <String>]`: The unique identifier of virtualEvent
    - `[VirtualEventPresenterId <String>]`: The unique identifier of virtualEventPresenter
    - `[VirtualEventSessionId <String>]`: The unique identifier of virtualEventSession
    - `[VirtualEventWebinarId <String>]`: The unique identifier of virtualEventWebinar

  `LASTMODIFIEDBY <IMicrosoftGraphIdentitySet>`: identitySet
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Application <IMicrosoftGraphIdentity>]`: identity
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[DisplayName <String>]`: The display name of the identity. Note that this might not always be available or up to date. For example, if a user changes their display name, the API might show the new value in a future response, but the items associated with the user won't show up as having changed when using delta.
      - `[Id <String>]`: Unique identifier for the identity.
    - `[Device <IMicrosoftGraphIdentity>]`: identity
    - `[User <IMicrosoftGraphIdentity>]`: identity

  `LOCALIZATIONS <IMicrosoftGraphPlannerPlanConfigurationLocalization[]>`: Localized names for the plan configuration.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketLocalization[]>]`: Localized names for configured buckets in the plan configuration.
      - `[ExternalBucketId <String>]`: Application-specified identifier of the bucket.
      - `[Name <String>]`: Name of the bucket.
    - `[LanguageTag <String>]`: The language code associated with the localized names in this object.
    - `[PlanTitle <String>]`: Localized title of the plan.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IBookingsIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerPlanConfiguration" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerPlanConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBusinessScenarioPlannerPlanConfiguration
  href: /powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerPlanConfiguration?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfiguration -BusinessScenarioId <String>

   [-AdditionalProperties <Hashtable>] [-Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketDefinition[]>]

   [-CreatedBy <IMicrosoftGraphIdentitySet>] [-CreatedDateTime <DateTime>] [-DefaultLanguage <String>]

   [-Id <String>] [-LastModifiedBy <IMicrosoftGraphIdentitySet>] [-LastModifiedDateTime <DateTime>]

   [-Localizations <IMicrosoftGraphPlannerPlanConfigurationLocalization[]>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfiguration -BusinessScenarioId <String>

   -BodyParameter <IMicrosoftGraphPlannerPlanConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfiguration -InputObject <IBookingsIdentity>

   [-AdditionalProperties <Hashtable>] [-Buckets <IMicrosoftGraphPlannerPlanConfigurationBucketDefinition[]>]

   [-CreatedBy <IMicrosoftGraphIdentitySet>] [-CreatedDateTime <DateTime>] [-DefaultLanguage <String>]

   [-Id <String>] [-LastModifiedBy <IMicrosoftGraphIdentitySet>] [-LastModifiedDateTime <DateTime>]

   [-Localizations <IMicrosoftGraphPlannerPlanConfigurationLocalization[]>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerPlanConfiguration -InputObject <IBookingsIdentity>

   -BodyParameter <IMicrosoftGraphPlannerPlanConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerPlanConfiguration" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    plannerPlanConfiguration
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerPlanConfigurationBucketDefinition" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Buckets
  description: |+
    List the buckets that should be created in the plan.
    To construct, see NOTES section for BUCKETS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BusinessScenarioId
  isRequired: true
  description: |+
    The unique identifier of businessScenario

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphIdentitySet" data-throw-if-not-resolved="False" />
  name: CreatedBy
  description: |+
    identitySet
    To construct, see NOTES section for CREATEDBY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CreatedDateTime
  description: |+
    The date and time when the plan configuration was created.
    The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time.
    For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DefaultLanguage
  description: |+
    The language code for the default language to be used for the names of the objects created for the plan.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IBookingsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphIdentitySet" data-throw-if-not-resolved="False" />
  name: LastModifiedBy
  description: |+
    identitySet
    To construct, see NOTES section for LASTMODIFIEDBY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastModifiedDateTime
  description: |+
    The date and time when the plan configuration was last modified.
    The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time.
    For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerPlanConfigurationLocalization" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Localizations
  description: |+
    Localized names for the plan configuration.
    To construct, see NOTES section for LOCALIZATIONS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Bookings.Update-MgBetaBusinessScenarioPlannerPlanConfiguration
name: Update-MgBetaBusinessScenarioPlannerPlanConfiguration
description: |-
  Update the properties of a plannerPlanConfiguration object for a businessScenario.
metadata:
  external help file: Microsoft.Graph.Beta.Bookings-help.xml
  Module Name: Microsoft.Graph.Beta.Bookings
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.bookings/update-mgbetabusinessscenarioplannerplanconfiguration
  schema: 2.0.0
