### YamlMime:PowershellCmdlet
summary: |-
  Update the properties of a plannerTaskConfiguration object.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgBusinessScenarioPlannerTaskConfiguration](/powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerTaskConfiguration?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.Bookings
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphPlannerTaskConfiguration>`: plannerTaskConfiguration
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[EditPolicy <IMicrosoftGraphPlannerTaskPolicy>]`: plannerTaskPolicy
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Rules <IMicrosoftGraphPlannerTaskRoleBasedRule[]>]`: The rules that should be enforced on the tasks when they are being changed outside of the scenario, based on the role of the caller.
        - `[DefaultRule <String>]`: Default rule that applies when a property or action-specific rule is not provided. Possible values are: Allow, Block
        - `[PropertyRule <IMicrosoftGraphPlannerTaskPropertyRule>]`: plannerTaskPropertyRule
          - `[(Any) <Object>]`: This indicates any property can be added to this object.
          - `[RuleKind <String>]`: plannerRuleKind
          - `[AppliedCategories <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
            - `[(Any) <Object>]`: This indicates any property can be added to this object.
            - `[DefaultRules <String[]>]`: The default rules that apply if no override matches to the current data.
            - `[Overrides <IMicrosoftGraphPlannerRuleOverride[]>]`: Overrides that specify different rules for specific data associated with the field.
              - `[Name <String>]`: Name of the override. Allowed override values will be dependent on the property affected by the rule.
              - `[Rules <String[]>]`: Overridden rules. These are used as rules for the override instead of the default rules.
          - `[Assignments <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
          - `[CheckLists <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
          - `[CompletionRequirements <String[]>]`: Rules and restrictions for completion requirements of the task. Accepted values are allow, add, remove, edit, and block.
          - `[Delete <String[]>]`: Rules and restrictions for deleting the task. Accepted values are allow and block.
          - `[DueDate <String[]>]`: Rules and restrictions for changing the due date of the task. Accepted values are allow and block.
          - `[Move <String[]>]`: Rules and restrictions for moving the task between buckets or plans. Accepted values are allow, moveBetweenPlans, moveBetweenBuckets, and block.
          - `[Notes <String[]>]`: Rules and restrictions for changing the notes of the task. Accepted values are allow and block.
          - `[Order <String[]>]`: Rules and restrictions for changing the order of the task. Accepted values are allow and block.
          - `[PercentComplete <String[]>]`: Rules and restrictions for changing the completion percentage of the task. Accepted values are allow, setToComplete, overrideRequirements, setToNotStarted, setToInProgress, and block.
          - `[PreviewType <String[]>]`: Rules and restrictions for changing the preview type of the task. Accepted values are allow and block.
          - `[Priority <String[]>]`: Rules and restrictions for changing the priority of the task. Accepted values are allow and block.
          - `[References <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
          - `[StartDate <String[]>]`: Rules and restrictions for changing the start date of the task. Accepted values are allow and block.
          - `[Title <String[]>]`: Rules and restrictions for changing the title of the task. Accepted values are allow and block.
        - `[Role <IMicrosoftGraphPlannerTaskConfigurationRoleBase>]`: plannerTaskConfigurationRoleBase
          - `[(Any) <Object>]`: This indicates any property can be added to this object.
          - `[RoleKind <String>]`: plannerUserRoleKind

  `EDITPOLICY <IMicrosoftGraphPlannerTaskPolicy>`: plannerTaskPolicy
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Rules <IMicrosoftGraphPlannerTaskRoleBasedRule[]>]`: The rules that should be enforced on the tasks when they are being changed outside of the scenario, based on the role of the caller.
      - `[DefaultRule <String>]`: Default rule that applies when a property or action-specific rule is not provided. Possible values are: Allow, Block
      - `[PropertyRule <IMicrosoftGraphPlannerTaskPropertyRule>]`: plannerTaskPropertyRule
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[RuleKind <String>]`: plannerRuleKind
        - `[AppliedCategories <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
          - `[(Any) <Object>]`: This indicates any property can be added to this object.
          - `[DefaultRules <String[]>]`: The default rules that apply if no override matches to the current data.
          - `[Overrides <IMicrosoftGraphPlannerRuleOverride[]>]`: Overrides that specify different rules for specific data associated with the field.
            - `[Name <String>]`: Name of the override. Allowed override values will be dependent on the property affected by the rule.
            - `[Rules <String[]>]`: Overridden rules. These are used as rules for the override instead of the default rules.
        - `[Assignments <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
        - `[CheckLists <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
        - `[CompletionRequirements <String[]>]`: Rules and restrictions for completion requirements of the task. Accepted values are allow, add, remove, edit, and block.
        - `[Delete <String[]>]`: Rules and restrictions for deleting the task. Accepted values are allow and block.
        - `[DueDate <String[]>]`: Rules and restrictions for changing the due date of the task. Accepted values are allow and block.
        - `[Move <String[]>]`: Rules and restrictions for moving the task between buckets or plans. Accepted values are allow, moveBetweenPlans, moveBetweenBuckets, and block.
        - `[Notes <String[]>]`: Rules and restrictions for changing the notes of the task. Accepted values are allow and block.
        - `[Order <String[]>]`: Rules and restrictions for changing the order of the task. Accepted values are allow and block.
        - `[PercentComplete <String[]>]`: Rules and restrictions for changing the completion percentage of the task. Accepted values are allow, setToComplete, overrideRequirements, setToNotStarted, setToInProgress, and block.
        - `[PreviewType <String[]>]`: Rules and restrictions for changing the preview type of the task. Accepted values are allow and block.
        - `[Priority <String[]>]`: Rules and restrictions for changing the priority of the task. Accepted values are allow and block.
        - `[References <IMicrosoftGraphPlannerFieldRules>]`: plannerFieldRules
        - `[StartDate <String[]>]`: Rules and restrictions for changing the start date of the task. Accepted values are allow and block.
        - `[Title <String[]>]`: Rules and restrictions for changing the title of the task. Accepted values are allow and block.
      - `[Role <IMicrosoftGraphPlannerTaskConfigurationRoleBase>]`: plannerTaskConfigurationRoleBase
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[RoleKind <String>]`: plannerUserRoleKind

  `INPUTOBJECT <IBookingsIdentity>`: Identity Parameter
    - `[AttendanceRecordId <String>]`: The unique identifier of attendanceRecord
    - `[BookingAppointmentId <String>]`: The unique identifier of bookingAppointment
    - `[BookingBusinessId <String>]`: The unique identifier of bookingBusiness
    - `[BookingCurrencyId <String>]`: The unique identifier of bookingCurrency
    - `[BookingCustomQuestionId <String>]`: The unique identifier of bookingCustomQuestion
    - `[BookingCustomerId <String>]`: The unique identifier of bookingCustomer
    - `[BookingServiceId <String>]`: The unique identifier of bookingService
    - `[BookingStaffMemberId <String>]`: The unique identifier of bookingStaffMember
    - `[BusinessScenarioId <String>]`: The unique identifier of businessScenario
    - `[BusinessScenarioTaskId <String>]`: The unique identifier of businessScenarioTask
    - `[CallRecordingId <String>]`: The unique identifier of callRecording
    - `[CallTranscriptId <String>]`: The unique identifier of callTranscript
    - `[MeetingAttendanceReportId <String>]`: The unique identifier of meetingAttendanceReport
    - `[MeetingRegistrantBaseId <String>]`: The unique identifier of meetingRegistrantBase
    - `[MeetingRegistrationQuestionId <String>]`: The unique identifier of meetingRegistrationQuestion
    - `[PlannerPlanConfigurationLocalizationId <String>]`: The unique identifier of plannerPlanConfigurationLocalization
    - `[VirtualEventId <String>]`: The unique identifier of virtualEvent
    - `[VirtualEventPresenterId <String>]`: The unique identifier of virtualEventPresenter
    - `[VirtualEventSessionId <String>]`: The unique identifier of virtualEventSession
    - `[VirtualEventWebinarId <String>]`: The unique identifier of virtualEventWebinar
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IBookingsIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerTaskConfiguration" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphPlannerTaskConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBusinessScenarioPlannerTaskConfiguration
  href: /powershell/module/Microsoft.Graph.Bookings/Update-MgBusinessScenarioPlannerTaskConfiguration?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaBusinessScenarioPlannerTaskConfiguration -BusinessScenarioId <String>

   [-AdditionalProperties <Hashtable>] [-EditPolicy <IMicrosoftGraphPlannerTaskPolicy>] [-Id <String>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerTaskConfiguration -BusinessScenarioId <String>

   -BodyParameter <IMicrosoftGraphPlannerTaskConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerTaskConfiguration -InputObject <IBookingsIdentity>

   [-AdditionalProperties <Hashtable>] [-EditPolicy <IMicrosoftGraphPlannerTaskPolicy>] [-Id <String>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaBusinessScenarioPlannerTaskConfiguration -InputObject <IBookingsIdentity>

   -BodyParameter <IMicrosoftGraphPlannerTaskConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerTaskConfiguration" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    plannerTaskConfiguration
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BusinessScenarioId
  isRequired: true
  description: |+
    The unique identifier of businessScenario

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphPlannerTaskPolicy" data-throw-if-not-resolved="False" />
  name: EditPolicy
  description: |+
    plannerTaskPolicy
    To construct, see NOTES section for EDITPOLICY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IBookingsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.Bookings.Update-MgBetaBusinessScenarioPlannerTaskConfiguration
name: Update-MgBetaBusinessScenarioPlannerTaskConfiguration
description: |-
  Update the properties of a plannerTaskConfiguration object.
metadata:
  external help file: Microsoft.Graph.Beta.Bookings-help.xml
  Module Name: Microsoft.Graph.Beta.Bookings
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.bookings/update-mgbetabusinessscenarioplannertaskconfiguration
  schema: 2.0.0
