### YamlMime:PowershellCmdlet
summary: |-
  Invoke function getOmaSettingPlainTextValue

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaDeviceManagementDeviceConfigurationOmaSettingPlainTextValue](/powershell/module/Microsoft.Graph.Beta.DeviceManagement.Functions/Get-MgBetaDeviceManagementDeviceConfigurationOmaSettingPlainTextValue?view=graph-powershell-beta)
module: Microsoft.Graph.DeviceManagement.Functions
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `INPUTOBJECT <IDeviceManagementFunctionsIdentity>`: Identity Parameter
    - `[Category <String>]`: Usage: category='{category}'
    - `[DeviceConfigurationId <String>]`: The unique identifier of deviceConfiguration
    - `[DomainName <String>]`: Usage: domainName='{domainName}'
    - `[Scope <String>]`: Usage: scope='{scope}'
    - `[SecretReferenceValueId <String>]`: Usage: secretReferenceValueId='{secretReferenceValueId}'
    - `[SummarizeBy <UserExperienceAnalyticsSummarizedBy?>]`: Usage: summarizeBy='{summarizeBy}'
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDeviceManagementFunctionsIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaDeviceManagementDeviceConfigurationOmaSettingPlainTextValue
  href: /powershell/module/Microsoft.Graph.Beta.DeviceManagement.Functions/Get-MgBetaDeviceManagementDeviceConfigurationOmaSettingPlainTextValue?view=graph-powershell-beta
syntaxes:
- >-
  Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue -DeviceConfigurationId <String>

   -SecretReferenceValueId <String> [<CommonParameters>]
- >-
  Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue

   -InputObject <IDeviceManagementFunctionsIdentity> [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DeviceConfigurationId
  isRequired: true
  description: |+
    The unique identifier of deviceConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDeviceManagementFunctionsIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SecretReferenceValueId
  isRequired: true
  description: |+
    Usage: secretReferenceValueId='{secretReferenceValueId}'

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.DeviceManagement.Functions.Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue
name: Get-MgDeviceManagementDeviceConfigurationOmaSettingPlainTextValue
description: |-
  Invoke function getOmaSettingPlainTextValue
metadata:
  external help file: Microsoft.Graph.DeviceManagement.Functions-help.xml
  Module Name: Microsoft.Graph.DeviceManagement.Functions
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devicemanagement.functions/get-mgdevicemanagementdeviceconfigurationomasettingplaintextvalue
  schema: 2.0.0
