### YamlMime:PowershellCmdlet
summary: |-
  Get the number of the resource

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount](/powershell/module/Microsoft.Graph.DeviceManagement/Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES
outputs:
- name: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount
  href: /powershell/module/Microsoft.Graph.DeviceManagement/Get-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount?view=graph-powershell-v1.0
syntaxes:
- >-
  Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount

   [-Filter <String>] [-Search <String>] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Filter items by property values

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Search
  description: |+
    Search items by search phrases

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount
name: Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount
description: |-
  Get the number of the resource
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/get-mgbetadevicemanagementuserexperienceanalyticapphealthapplicationperformancebyappversiondeviceidcount
  schema: 2.0.0
