### YamlMime:PowershellCmdlet
summary: |-
  The device configuration user state summary for this account.

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Get-MgDeviceManagementDeviceConfigurationUserStateSummary](/powershell/module/Microsoft.Graph.DeviceManagement/Get-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceConfigurationUserStateSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgDeviceManagementDeviceConfigurationUserStateSummary
  href: /powershell/module/Microsoft.Graph.DeviceManagement/Get-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0
syntaxes:
- >-
  Get-MgBetaDeviceManagementDeviceConfigurationUserStateSummary [-ExpandProperty <String[]>]

   [-Property <String[]>] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Get-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
name: Get-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
description: |-
  The device configuration user state summary for this account.
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/get-mgbetadevicemanagementdeviceconfigurationuserstatesummary
  schema: 2.0.0
