### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to configurationPolicyTemplates for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementConfigurationPolicyTemplate](/powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementConfigurationPolicyTemplate?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphDeviceManagementConfigurationPolicyTemplate>`: Device Management Configuration Policy Template
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[AllowUnmanagedSettings <Boolean?>]`: Allow unmanaged setting templates
    - `[BaseId <String>]`: Template base identifier
    - `[Description <String>]`: Template description
    - `[DisplayName <String>]`: Template display name
    - `[DisplayVersion <String>]`: Description of template version
    - `[LifecycleState <DeviceManagementTemplateLifecycleState?>]`: Describes current lifecycle state of a template
    - `[Platforms <DeviceManagementConfigurationPlatforms?>]`: Supported platform types.
    - `[SettingTemplates <IMicrosoftGraphDeviceManagementConfigurationSettingTemplate[]>]`: Setting templates
      - `[Id <String>]`: The unique identifier for an entity. Read-only.
      - `[SettingDefinitions <IMicrosoftGraphDeviceManagementConfigurationSettingDefinition[]>]`: List of related Setting Definitions
        - `[Id <String>]`: The unique identifier for an entity. Read-only.
        - `[AccessTypes <String>]`: deviceManagementConfigurationSettingAccessTypes
        - `[Applicability <IMicrosoftGraphDeviceManagementConfigurationSettingApplicability>]`: deviceManagementConfigurationSettingApplicability
          - `[(Any) <Object>]`: This indicates any property can be added to this object.
          - `[Description <String>]`: description of the setting
          - `[DeviceMode <DeviceManagementConfigurationDeviceMode?>]`: Describes applicability for the mode the device is in
          - `[Platform <DeviceManagementConfigurationPlatforms?>]`: Supported platform types.
          - `[Technologies <DeviceManagementConfigurationTechnologies?>]`: Describes which technology this setting can be deployed with
        - `[BaseUri <String>]`: Base CSP Path
        - `[CategoryId <String>]`: Specifies the area group under which the setting is configured in a specified configuration service provider (CSP)
        - `[Description <String>]`: Description of the item
        - `[DisplayName <String>]`: Display name of the item
        - `[HelpText <String>]`: Help text of the item
        - `[InfoUrls <String[]>]`: List of links more info for the setting can be found at
        - `[Keywords <String[]>]`: Tokens which to search settings on
        - `[Name <String>]`: Name of the item
        - `[Occurrence <IMicrosoftGraphDeviceManagementConfigurationSettingOccurrence>]`: deviceManagementConfigurationSettingOccurrence
          - `[(Any) <Object>]`: This indicates any property can be added to this object.
          - `[MaxDeviceOccurrence <Int32?>]`: Maximum times setting can be set on device.
          - `[MinDeviceOccurrence <Int32?>]`: Minimum times setting can be set on device. A MinDeviceOccurrence of 0 means setting is optional
        - `[OffsetUri <String>]`: Offset CSP Path from Base
        - `[ReferredSettingInformationList <IMicrosoftGraphDeviceManagementConfigurationReferredSettingInformation[]>]`: List of referred setting information.
          - `[SettingDefinitionId <String>]`: Setting definition id that is being referred to a setting. Applicable for reusable setting
        - `[RootDefinitionId <String>]`: Root setting definition if the setting is a child setting.
        - `[SettingUsage <DeviceManagementConfigurationSettingUsage?>]`: Supported setting types
        - `[UxBehavior <DeviceManagementConfigurationControlType?>]`: Setting control type representation in the UX
        - `[Version <String>]`: Item Version
        - `[Visibility <DeviceManagementConfigurationSettingVisibility?>]`: Supported setting types
      - `[SettingInstanceTemplate <IMicrosoftGraphDeviceManagementConfigurationSettingInstanceTemplate>]`: Setting Instance Template
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[IsRequired <Boolean?>]`: Indicates if a policy must specify this setting.
        - `[SettingDefinitionId <String>]`: Setting Definition Id
        - `[SettingInstanceTemplateId <String>]`: Setting Instance Template Id
    - `[Technologies <DeviceManagementConfigurationTechnologies?>]`: Describes which technology this setting can be deployed with
    - `[TemplateFamily <DeviceManagementConfigurationTemplateFamily?>]`: Describes the TemplateFamily for the Template entity

  `SETTINGTEMPLATES <IMicrosoftGraphDeviceManagementConfigurationSettingTemplate[]>`: Setting templates
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[SettingDefinitions <IMicrosoftGraphDeviceManagementConfigurationSettingDefinition[]>]`: List of related Setting Definitions
      - `[Id <String>]`: The unique identifier for an entity. Read-only.
      - `[AccessTypes <String>]`: deviceManagementConfigurationSettingAccessTypes
      - `[Applicability <IMicrosoftGraphDeviceManagementConfigurationSettingApplicability>]`: deviceManagementConfigurationSettingApplicability
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[Description <String>]`: description of the setting
        - `[DeviceMode <DeviceManagementConfigurationDeviceMode?>]`: Describes applicability for the mode the device is in
        - `[Platform <DeviceManagementConfigurationPlatforms?>]`: Supported platform types.
        - `[Technologies <DeviceManagementConfigurationTechnologies?>]`: Describes which technology this setting can be deployed with
      - `[BaseUri <String>]`: Base CSP Path
      - `[CategoryId <String>]`: Specifies the area group under which the setting is configured in a specified configuration service provider (CSP)
      - `[Description <String>]`: Description of the item
      - `[DisplayName <String>]`: Display name of the item
      - `[HelpText <String>]`: Help text of the item
      - `[InfoUrls <String[]>]`: List of links more info for the setting can be found at
      - `[Keywords <String[]>]`: Tokens which to search settings on
      - `[Name <String>]`: Name of the item
      - `[Occurrence <IMicrosoftGraphDeviceManagementConfigurationSettingOccurrence>]`: deviceManagementConfigurationSettingOccurrence
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
        - `[MaxDeviceOccurrence <Int32?>]`: Maximum times setting can be set on device.
        - `[MinDeviceOccurrence <Int32?>]`: Minimum times setting can be set on device. A MinDeviceOccurrence of 0 means setting is optional
      - `[OffsetUri <String>]`: Offset CSP Path from Base
      - `[ReferredSettingInformationList <IMicrosoftGraphDeviceManagementConfigurationReferredSettingInformation[]>]`: List of referred setting information.
        - `[SettingDefinitionId <String>]`: Setting definition id that is being referred to a setting. Applicable for reusable setting
      - `[RootDefinitionId <String>]`: Root setting definition if the setting is a child setting.
      - `[SettingUsage <DeviceManagementConfigurationSettingUsage?>]`: Supported setting types
      - `[UxBehavior <DeviceManagementConfigurationControlType?>]`: Setting control type representation in the UX
      - `[Version <String>]`: Item Version
      - `[Visibility <DeviceManagementConfigurationSettingVisibility?>]`: Supported setting types
    - `[SettingInstanceTemplate <IMicrosoftGraphDeviceManagementConfigurationSettingInstanceTemplate>]`: Setting Instance Template
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[IsRequired <Boolean?>]`: Indicates if a policy must specify this setting.
      - `[SettingDefinitionId <String>]`: Setting Definition Id
      - `[SettingInstanceTemplateId <String>]`: Setting Instance Template Id
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceManagementConfigurationPolicyTemplate" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceManagementConfigurationPolicyTemplate" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementConfigurationPolicyTemplate
  href: /powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementConfigurationPolicyTemplate?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementConfigurationPolicyTemplate [-AdditionalProperties <Hashtable>]

   [-AllowUnmanagedSettings] [-BaseId <String>] [-Description <String>] [-DisplayName <String>]

   [-DisplayVersion <String>] [-Id <String>] [-LifecycleState <DeviceManagementTemplateLifecycleState>]

   [-Platforms <DeviceManagementConfigurationPlatforms>]

   [-SettingTemplates <IMicrosoftGraphDeviceManagementConfigurationSettingTemplate[]>]

   [-Technologies <DeviceManagementConfigurationTechnologies>]

   [-TemplateFamily <DeviceManagementConfigurationTemplateFamily>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementConfigurationPolicyTemplate

   -BodyParameter <IMicrosoftGraphDeviceManagementConfigurationPolicyTemplate> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AllowUnmanagedSettings
  description: |+
    Allow unmanaged setting templates

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: BaseId
  description: |+
    Template base identifier

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphDeviceManagementConfigurationPolicyTemplate" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Device Management Configuration Policy Template
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Template description

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Template display name

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayVersion
  description: |+
    Description of template version

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DeviceManagementTemplateLifecycleState" data-throw-if-not-resolved="False" />
  name: LifecycleState
  description: |+
    Describes current lifecycle state of a template

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DeviceManagementConfigurationPlatforms" data-throw-if-not-resolved="False" />
  name: Platforms
  description: |+
    Supported platform types.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphDeviceManagementConfigurationSettingTemplate" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SettingTemplates
  description: |+
    Setting templates
    To construct, see NOTES section for SETTINGTEMPLATES properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DeviceManagementConfigurationTechnologies" data-throw-if-not-resolved="False" />
  name: Technologies
  description: |+
    Describes which technology this setting can be deployed with

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DeviceManagementConfigurationTemplateFamily" data-throw-if-not-resolved="False" />
  name: TemplateFamily
  description: |+
    Describes the TemplateFamily for the Template entity

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.New-MgBetaDeviceManagementConfigurationPolicyTemplate
name: New-MgBetaDeviceManagementConfigurationPolicyTemplate
description: |-
  Create new navigation property to configurationPolicyTemplates for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/new-mgbetadevicemanagementconfigurationpolicytemplate
  schema: 2.0.0
