### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to userExperienceAnalyticsAppHealthApplicationPerformanceByOSVersion for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion](/powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion>`: The user experience analytics application performance entity contains app performance details by OS version.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[ActiveDeviceCount <Int32?>]`: The number of devices where the application has been active. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppCrashCount <Int32?>]`: The number of crashes for the application. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[AppDisplayName <String>]`: The friendly name of the application. Possible values are: Outlook, Excel. Supports: $select, $OrderBy. Read-only.
    - `[AppName <String>]`: The name of the application. Possible values are: outlook.exe, excel.exe. Supports: $select, $OrderBy. Read-only.
    - `[AppPublisher <String>]`: The publisher of the application. Supports: $select, $OrderBy. Read-only.
    - `[AppUsageDuration <Int32?>]`: The total usage time of the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[MeanTimeToFailureInMinutes <Int32?>]`: The mean time to failure for the application in minutes. Valid values 0 to 2147483647. Supports: $select, $OrderBy. Read-only. Valid values -2147483648 to 2147483647
    - `[OSBuildNumber <String>]`: The OS build number of the application. Supports: $select, $OrderBy. Read-only.
    - `[OSVersion <String>]`: The OS version of the application. Supports: $select, $OrderBy. Read-only.
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion
  href: /powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion

   [-ActiveDeviceCount <Int32>] [-AdditionalProperties <Hashtable>] [-AppCrashCount <Int32>]

   [-AppDisplayName <String>] [-AppName <String>] [-AppPublisher <String>] [-AppUsageDuration <Int32>]

   [-Id <String>] [-MeanTimeToFailureInMinutes <Int32>] [-OSBuildNumber <String>] [-OSVersion <String>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion

   -BodyParameter <IMicrosoftGraphUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ActiveDeviceCount
  description: |+
    The number of devices where the application has been active.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppCrashCount
  description: |+
    The number of crashes for the application.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppDisplayName
  description: |+
    The friendly name of the application.
    Possible values are: Outlook, Excel.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppName
  description: |+
    The name of the application.
    Possible values are: outlook.exe, excel.exe.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppPublisher
  description: |+
    The publisher of the application.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AppUsageDuration
  description: |+
    The total usage time of the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphUserExperienceAnalyticsAppHealthAppPerformanceByOSVersion" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    The user experience analytics application performance entity contains app performance details by OS version.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MeanTimeToFailureInMinutes
  description: |+
    The mean time to failure for the application in minutes.
    Valid values 0 to 2147483647.
    Supports: $select, $OrderBy.
    Read-only.
    Valid values -2147483648 to 2147483647

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OSBuildNumber
  description: |+
    The OS build number of the application.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OSVersion
  description: |+
    The OS version of the application.
    Supports: $select, $OrderBy.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion
name: New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion
description: |-
  Create new navigation property to userExperienceAnalyticsAppHealthApplicationPerformanceByOSVersion for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/new-mgbetadevicemanagementuserexperienceanalyticapphealthapplicationperformancebyosversion
  schema: 2.0.0
