### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to androidForWorkAppConfigurationSchemas for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementAndroidForWorkAppConfigurationSchema](/powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementAndroidForWorkAppConfigurationSchema?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphAndroidForWorkAppConfigurationSchema>`: Schema describing an Android for Work application's custom configurations.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[ExampleJson <Byte[]>]`: UTF8 encoded byte array containing example JSON string conforming to this schema that demonstrates how to set the configuration for this app
    - `[SchemaItems <IMicrosoftGraphAndroidForWorkAppConfigurationSchemaItem[]>]`: Collection of items each representing a named configuration option in the schema
      - `[DataType <String>]`: Data type for a configuration item inside an Android for Work application's custom configuration schema
      - `[DefaultBoolValue <Boolean?>]`: Default value for boolean type items, if specified by the app developer
      - `[DefaultIntValue <Int32?>]`: Default value for integer type items, if specified by the app developer
      - `[DefaultStringArrayValue <String[]>]`: Default value for string array type items, if specified by the app developer
      - `[DefaultStringValue <String>]`: Default value for string type items, if specified by the app developer
      - `[Description <String>]`: Description of what the item controls within the application
      - `[DisplayName <String>]`: Human readable name
      - `[SchemaItemKey <String>]`: Unique key the application uses to identify the item
      - `[Selections <IMicrosoftGraphKeyValuePair[]>]`: List of human readable name/value pairs for the valid values that can be set for this item (Choice and Multiselect items only)
        - `[Name <String>]`: Name for this key-value pair
        - `[Value <String>]`: Value for this key-value pair

  `SCHEMAITEMS <IMicrosoftGraphAndroidForWorkAppConfigurationSchemaItem[]>`: Collection of items each representing a named configuration option in the schema
    - `[DataType <String>]`: Data type for a configuration item inside an Android for Work application's custom configuration schema
    - `[DefaultBoolValue <Boolean?>]`: Default value for boolean type items, if specified by the app developer
    - `[DefaultIntValue <Int32?>]`: Default value for integer type items, if specified by the app developer
    - `[DefaultStringArrayValue <String[]>]`: Default value for string array type items, if specified by the app developer
    - `[DefaultStringValue <String>]`: Default value for string type items, if specified by the app developer
    - `[Description <String>]`: Description of what the item controls within the application
    - `[DisplayName <String>]`: Human readable name
    - `[SchemaItemKey <String>]`: Unique key the application uses to identify the item
    - `[Selections <IMicrosoftGraphKeyValuePair[]>]`: List of human readable name/value pairs for the valid values that can be set for this item (Choice and Multiselect items only)
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphAndroidForWorkAppConfigurationSchema" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphAndroidForWorkAppConfigurationSchema" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementAndroidForWorkAppConfigurationSchema
  href: /powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementAndroidForWorkAppConfigurationSchema?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema [-AdditionalProperties <Hashtable>]

   [-ExampleJsonInputFile <String>] [-Id <String>]

   [-SchemaItems <IMicrosoftGraphAndroidForWorkAppConfigurationSchemaItem[]>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema

   -BodyParameter <IMicrosoftGraphAndroidForWorkAppConfigurationSchema> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphAndroidForWorkAppConfigurationSchema" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Schema describing an Android for Work application's custom configurations.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExampleJsonInputFile
  description: |+
    Input File for ExampleJson (UTF8 encoded byte array containing example JSON string conforming to this schema that demonstrates how to set the configuration for this app)

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphAndroidForWorkAppConfigurationSchemaItem" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SchemaItems
  description: |+
    Collection of items each representing a named configuration option in the schema
    To construct, see NOTES section for SCHEMAITEMS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.New-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema
name: New-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema
description: |-
  Create new navigation property to androidForWorkAppConfigurationSchemas for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/new-mgbetadevicemanagementandroidforworkappconfigurationschema
  schema: 2.0.0
