### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to microsoftTunnelConfigurations for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementMicrosoftTunnelConfiguration](/powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementMicrosoftTunnelConfiguration?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `ADVANCEDSETTINGS <IMicrosoftGraphKeyValuePair[]>`: Additional settings that may be applied to the server
    - `[Name <String>]`: Name for this key-value pair
    - `[Value <String>]`: Value for this key-value pair

  `BODYPARAMETER <IMicrosoftGraphMicrosoftTunnelConfiguration>`: Entity that represents a collection of Microsoft Tunnel settings
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[AdvancedSettings <IMicrosoftGraphKeyValuePair[]>]`: Additional settings that may be applied to the server
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[DefaultDomainSuffix <String>]`: The Default Domain appendix that will be used by the clients
    - `[Description <String>]`: The configuration's description (optional)
    - `[DisableUdpConnections <Boolean?>]`: When DisableUdpConnections is set, the clients and VPN server will not use DTLS connections to transfer data.
    - `[DisplayName <String>]`: The display name for the server configuration. This property is required when a server is created.
    - `[DnsServers <String[]>]`: The DNS servers that will be used by the clients
    - `[LastUpdateDateTime <DateTime?>]`: When the configuration was last updated
    - `[ListenPort <Int32?>]`: The port that both TCP and UPD will listen over on the server
    - `[Network <String>]`: The subnet that will be used to allocate virtual address for the clients
    - `[RoleScopeTagIds <String[]>]`: List of Scope Tags for this Entity instance
    - `[RouteExcludes <String[]>]`: Subsets of the routes that will not be routed by the server
    - `[RouteIncludes <String[]>]`: The routes that will be routed by the server
    - `[RoutesExclude <String[]>]`: Subsets of the routes that will not be routed by the server. This property is going to be deprecated with the option of using the new property, 'RouteExcludes'.
    - `[RoutesInclude <String[]>]`: The routes that will be routed by the server. This property is going to be deprecated with the option of using the new property, 'RouteIncludes'.
    - `[SplitDns <String[]>]`: The domains that will be resolved using the provided dns servers
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphMicrosoftTunnelConfiguration" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphMicrosoftTunnelConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementMicrosoftTunnelConfiguration
  href: /powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementMicrosoftTunnelConfiguration?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementMicrosoftTunnelConfiguration [-AdditionalProperties <Hashtable>]

   [-AdvancedSettings <IMicrosoftGraphKeyValuePair[]>] [-DefaultDomainSuffix <String>] [-Description <String>]

   [-DisableUdpConnections] [-DisplayName <String>] [-DnsServers <String[]>] [-Id <String>]

   [-LastUpdateDateTime <DateTime>] [-ListenPort <Int32>] [-Network <String>] [-RoleScopeTagIds <String[]>]

   [-RouteExcludes <String[]>] [-RouteIncludes <String[]>] [-RoutesExclude <String[]>]

   [-RoutesInclude <String[]>] [-SplitDns <String[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementMicrosoftTunnelConfiguration

   -BodyParameter <IMicrosoftGraphMicrosoftTunnelConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphKeyValuePair" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AdvancedSettings
  description: |+
    Additional settings that may be applied to the server
    To construct, see NOTES section for ADVANCEDSETTINGS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphMicrosoftTunnelConfiguration" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Entity that represents a collection of Microsoft Tunnel settings
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DefaultDomainSuffix
  description: |+
    The Default Domain appendix that will be used by the clients

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    The configuration's description (optional)

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisableUdpConnections
  description: |+
    When DisableUdpConnections is set, the clients and VPN server will not use DTLS connections to transfer data.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    The display name for the server configuration.
    This property is required when a server is created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: DnsServers
  description: |+
    The DNS servers that will be used by the clients

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastUpdateDateTime
  description: |+
    When the configuration was last updated

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ListenPort
  description: |+
    The port that both TCP and UPD will listen over on the server

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Network
  description: |+
    The subnet that will be used to allocate virtual address for the clients

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RoleScopeTagIds
  description: |+
    List of Scope Tags for this Entity instance

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RouteExcludes
  description: |+
    Subsets of the routes that will not be routed by the server

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RouteIncludes
  description: |+
    The routes that will be routed by the server

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RoutesExclude
  description: |+
    Subsets of the routes that will not be routed by the server.
    This property is going to be deprecated with the option of using the new property, 'RouteExcludes'.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RoutesInclude
  description: |+
    The routes that will be routed by the server.
    This property is going to be deprecated with the option of using the new property, 'RouteIncludes'.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SplitDns
  description: |+
    The domains that will be resolved using the provided dns servers

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.New-MgBetaDeviceManagementMicrosoftTunnelConfiguration
name: New-MgBetaDeviceManagementMicrosoftTunnelConfiguration
description: |-
  Create new navigation property to microsoftTunnelConfigurations for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/new-mgbetadevicemanagementmicrosofttunnelconfiguration
  schema: 2.0.0
