### YamlMime:PowershellCmdlet
summary: |-
  Create new navigation property to deviceCompliancePolicySettingStateSummaries for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary](/powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphDeviceCompliancePolicySettingStateSummary>`: Device Compilance Policy Setting State summary across the account.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[CompliantDeviceCount <Int32?>]`: Number of compliant devices
    - `[ConflictDeviceCount <Int32?>]`: Number of conflict devices
    - `[DeviceComplianceSettingStates <IMicrosoftGraphDeviceComplianceSettingState[]>]`: Not yet documented
      - `[Id <String>]`: The unique identifier for an entity. Read-only.
      - `[ComplianceGracePeriodExpirationDateTime <DateTime?>]`: The DateTime when device compliance grace period expires
      - `[DeviceId <String>]`: The Device Id that is being reported
      - `[DeviceModel <String>]`: The device model that is being reported
      - `[DeviceName <String>]`: The Device Name that is being reported
      - `[PlatformType <DeviceType?>]`: Device type.
      - `[Setting <String>]`: The setting class name and property name.
      - `[SettingName <String>]`: The Setting Name that is being reported
      - `[State <String>]`: complianceStatus
      - `[UserEmail <String>]`: The User email address that is being reported
      - `[UserId <String>]`: The user Id that is being reported
      - `[UserName <String>]`: The User Name that is being reported
      - `[UserPrincipalName <String>]`: The User PrincipalName that is being reported
    - `[ErrorDeviceCount <Int32?>]`: Number of error devices
    - `[NonCompliantDeviceCount <Int32?>]`: Number of NonCompliant devices
    - `[NotApplicableDeviceCount <Int32?>]`: Number of not applicable devices
    - `[PlatformType <PolicyPlatformType?>]`: Supported platform types for policies.
    - `[RemediatedDeviceCount <Int32?>]`: Number of remediated devices
    - `[Setting <String>]`: The setting class name and property name.
    - `[SettingName <String>]`: Name of the setting.
    - `[UnknownDeviceCount <Int32?>]`: Number of unknown devices

  `DEVICECOMPLIANCESETTINGSTATES <IMicrosoftGraphDeviceComplianceSettingState[]>`: Not yet documented
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[ComplianceGracePeriodExpirationDateTime <DateTime?>]`: The DateTime when device compliance grace period expires
    - `[DeviceId <String>]`: The Device Id that is being reported
    - `[DeviceModel <String>]`: The device model that is being reported
    - `[DeviceName <String>]`: The Device Name that is being reported
    - `[PlatformType <DeviceType?>]`: Device type.
    - `[Setting <String>]`: The setting class name and property name.
    - `[SettingName <String>]`: The Setting Name that is being reported
    - `[State <String>]`: complianceStatus
    - `[UserEmail <String>]`: The User email address that is being reported
    - `[UserId <String>]`: The user Id that is being reported
    - `[UserName <String>]`: The User Name that is being reported
    - `[UserPrincipalName <String>]`: The User PrincipalName that is being reported
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceCompliancePolicySettingStateSummary" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceCompliancePolicySettingStateSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary
  href: /powershell/module/Microsoft.Graph.DeviceManagement/New-MgDeviceManagementDeviceCompliancePolicySettingStateSummary?view=graph-powershell-v1.0
syntaxes:
- >-
  New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary [-AdditionalProperties <Hashtable>]

   [-CompliantDeviceCount <Int32>] [-ConflictDeviceCount <Int32>]

   [-DeviceComplianceSettingStates <IMicrosoftGraphDeviceComplianceSettingState[]>] [-ErrorDeviceCount <Int32>]

   [-Id <String>] [-NonCompliantDeviceCount <Int32>] [-NotApplicableDeviceCount <Int32>]

   [-PlatformType <PolicyPlatformType>] [-RemediatedDeviceCount <Int32>] [-Setting <String>]

   [-SettingName <String>] [-UnknownDeviceCount <Int32>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary

   -BodyParameter <IMicrosoftGraphDeviceCompliancePolicySettingStateSummary> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphDeviceCompliancePolicySettingStateSummary" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Device Compilance Policy Setting State summary across the account.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CompliantDeviceCount
  description: |+
    Number of compliant devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ConflictDeviceCount
  description: |+
    Number of conflict devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphDeviceComplianceSettingState" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: DeviceComplianceSettingStates
  description: |+
    Not yet documented
    To construct, see NOTES section for DEVICECOMPLIANCESETTINGSTATES properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ErrorDeviceCount
  description: |+
    Number of error devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NonCompliantDeviceCount
  description: |+
    Number of NonCompliant devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NotApplicableDeviceCount
  description: |+
    Number of not applicable devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PolicyPlatformType" data-throw-if-not-resolved="False" />
  name: PlatformType
  description: |+
    Supported platform types for policies.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RemediatedDeviceCount
  description: |+
    Number of remediated devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Setting
  description: |+
    The setting class name and property name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SettingName
  description: |+
    Name of the setting.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: UnknownDeviceCount
  description: |+
    Number of unknown devices

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary
name: New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary
description: |-
  Create new navigation property to deviceCompliancePolicySettingStateSummaries for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/new-mgbetadevicemanagementdevicecompliancepolicysettingstatesummary
  schema: 2.0.0
