### YamlMime:PowershellCmdlet
summary: |-
  Delete navigation property deviceConfigurationUserStateSummaries for deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Remove-MgDeviceManagementDeviceConfigurationUserStateSummary](/powershell/module/Microsoft.Graph.DeviceManagement/Remove-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES
outputs:
- name: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Remove-MgDeviceManagementDeviceConfigurationUserStateSummary
  href: /powershell/module/Microsoft.Graph.DeviceManagement/Remove-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0
syntaxes:
- >-
  Remove-MgBetaDeviceManagementDeviceConfigurationUserStateSummary [-IfMatch <String>] [-PassThru] [-WhatIf]

   [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IfMatch
  description: |+
    ETag

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns true when the command succeeds

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Remove-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
name: Remove-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
description: |-
  Delete navigation property deviceConfigurationUserStateSummaries for deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/remove-mgbetadevicemanagementdeviceconfigurationuserstatesummary
  schema: 2.0.0
