### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property deviceConfigurationUserStateSummaries in deviceManagement

  > [!NOTE]
  > To view the v1.0 release of this cmdlet, view [Update-MgDeviceManagementDeviceConfigurationUserStateSummary](/powershell/module/Microsoft.Graph.DeviceManagement/Update-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0)
module: Microsoft.Graph.Beta.DeviceManagement
notes: |-
  ALIASES

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphDeviceConfigurationUserStateSummary>`: deviceConfigurationUserStateSummary
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique identifier for an entity. Read-only.
    - `[CompliantUserCount <Int32?>]`: Number of compliant users
    - `[ConflictUserCount <Int32?>]`: Number of conflict users
    - `[ErrorUserCount <Int32?>]`: Number of error users
    - `[NonCompliantUserCount <Int32?>]`: Number of NonCompliant users
    - `[NotApplicableUserCount <Int32?>]`: Number of not applicable users
    - `[RemediatedUserCount <Int32?>]`: Number of remediated users
    - `[UnknownUserCount <Int32?>]`: Number of unknown users
inputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceConfigurationUserStateSummary" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphDeviceConfigurationUserStateSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgDeviceManagementDeviceConfigurationUserStateSummary
  href: /powershell/module/Microsoft.Graph.DeviceManagement/Update-MgDeviceManagementDeviceConfigurationUserStateSummary?view=graph-powershell-v1.0
syntaxes:
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationUserStateSummary [-AdditionalProperties <Hashtable>]

   [-CompliantUserCount <Int32>] [-ConflictUserCount <Int32>] [-ErrorUserCount <Int32>] [-Id <String>]

   [-NonCompliantUserCount <Int32>] [-NotApplicableUserCount <Int32>] [-RemediatedUserCount <Int32>]

   [-UnknownUserCount <Int32>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgBetaDeviceManagementDeviceConfigurationUserStateSummary

   -BodyParameter <IMicrosoftGraphDeviceConfigurationUserStateSummary> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphDeviceConfigurationUserStateSummary" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    deviceConfigurationUserStateSummary
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CompliantUserCount
  description: |+
    Number of compliant users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ConflictUserCount
  description: |+
    Number of conflict users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ErrorUserCount
  description: |+
    Number of error users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique identifier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NonCompliantUserCount
  description: |+
    Number of NonCompliant users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NotApplicableUserCount
  description: |+
    Number of not applicable users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: RemediatedUserCount
  description: |+
    Number of remediated users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: UnknownUserCount
  description: |+
    Number of unknown users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Beta.DeviceManagement.Update-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
name: Update-MgBetaDeviceManagementDeviceConfigurationUserStateSummary
description: |-
  Update the navigation property deviceConfigurationUserStateSummaries in deviceManagement
metadata:
  external help file: Microsoft.Graph.Beta.DeviceManagement-help.xml
  Module Name: Microsoft.Graph.Beta.DeviceManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.beta.devicemanagement/update-mgbetadevicemanagementdeviceconfigurationuserstatesummary
  schema: 2.0.0
