### YamlMime:PowershellCmdlet
summary: |-
  The list of group assignemenets for app configration.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignment](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignment?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  Please use Get-Help -Online.
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationAssignment" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignment
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtMobileAppConfigurationAssignment?view=graph-powershell-beta
- text: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationassignment
  href: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationassignment
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Get-MgDeviceAppMgtMobileAppConfigurationAssignment
name: Get-MgDeviceAppMgtMobileAppConfigurationAssignment
description: |-
  The list of group assignemenets for app configration.
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationassignment
  schema: 2.0.0
