### YamlMime:PowershellCmdlet
summary: |-
  Navigation property to list of inclusion and exclusion groups to which the policy is deployed.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  Please use Get-Help -Online.
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphTargetedManagedAppPolicyAssignment" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtTargetedManagedAppConfigurationAssignment?view=graph-powershell-beta
- text: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgttargetedmanagedappconfigurationassignment
  href: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgttargetedmanagedappconfigurationassignment
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment
name: Get-MgDeviceAppMgtTargetedManagedAppConfigurationAssignment
description: |-
  Navigation property to list of inclusion and exclusion groups to which the policy is deployed.
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgttargetedmanagedappconfigurationassignment
  schema: 2.0.0
