### YamlMime:PowershellCmdlet
summary: |-
  Navigation property to deployment summary of the configuration.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  ALIASES

  Get-MgDeviceAppMgtDefaultManagedAppProtectionDeploymentSummary

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `INPUTOBJECT <IDevicesCorporateManagementIdentity>`: Identity Parameter
    - `[AndroidManagedAppProtectionId <String>]`: The unique identifier of androidManagedAppProtection
    - `[DefaultManagedAppProtectionId <String>]`: The unique identifier of defaultManagedAppProtection
    - `[DeviceCompliancePolicyStateId <String>]`: The unique identifier of deviceCompliancePolicyState
    - `[DeviceConfigurationStateId <String>]`: The unique identifier of deviceConfigurationState
    - `[DeviceInstallStateId <String>]`: The unique identifier of deviceInstallState
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DeviceManagementTroubleshootingEventId <String>]`: The unique identifier of deviceManagementTroubleshootingEvent
    - `[IosManagedAppProtectionId <String>]`: The unique identifier of iosManagedAppProtection
    - `[ManagedAppOperationId <String>]`: The unique identifier of managedAppOperation
    - `[ManagedAppPolicyId <String>]`: The unique identifier of managedAppPolicy
    - `[ManagedAppRegistrationId <String>]`: The unique identifier of managedAppRegistration
    - `[ManagedAppStatusId <String>]`: The unique identifier of managedAppStatus
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[ManagedDeviceMobileAppConfigurationAssignmentId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationAssignment
    - `[ManagedDeviceMobileAppConfigurationDeviceStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationDeviceStatus
    - `[ManagedDeviceMobileAppConfigurationId <String>]`: The unique identifier of managedDeviceMobileAppConfiguration
    - `[ManagedDeviceMobileAppConfigurationUserStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationUserStatus
    - `[ManagedEBookAssignmentId <String>]`: The unique identifier of managedEBookAssignment
    - `[ManagedEBookId <String>]`: The unique identifier of managedEBook
    - `[ManagedMobileAppId <String>]`: The unique identifier of managedMobileApp
    - `[MdmWindowsInformationProtectionPolicyId <String>]`: The unique identifier of mdmWindowsInformationProtectionPolicy
    - `[MobileAppAssignmentId <String>]`: The unique identifier of mobileAppAssignment
    - `[MobileAppCategoryId <String>]`: The unique identifier of mobileAppCategory
    - `[MobileAppId <String>]`: The unique identifier of mobileApp
    - `[TargetedManagedAppConfigurationId <String>]`: The unique identifier of targetedManagedAppConfiguration
    - `[TargetedManagedAppPolicyAssignmentId <String>]`: The unique identifier of targetedManagedAppPolicyAssignment
    - `[UserId <String>]`: The unique identifier of user
    - `[UserInstallStateSummaryId <String>]`: The unique identifier of userInstallStateSummary
    - `[VppTokenId <String>]`: The unique identifier of vppToken
    - `[WindowsDeviceMalwareStateId <String>]`: The unique identifier of windowsDeviceMalwareState
    - `[WindowsInformationProtectionAppLockerFileId <String>]`: The unique identifier of windowsInformationProtectionAppLockerFile
    - `[WindowsInformationProtectionPolicyId <String>]`: The unique identifier of windowsInformationProtectionPolicy
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphManagedAppPolicyDeploymentSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary?view=graph-powershell-beta
syntaxes:
- >-
  Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary -DefaultManagedAppProtectionId <String>

   [-ExpandProperty <String[]>] [-Property <String[]>] [<CommonParameters>]
- >-
  Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary

   -InputObject <IDevicesCorporateManagementIdentity> [-ExpandProperty <String[]>] [-Property <String[]>]

   [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DefaultManagedAppProtectionId
  isRequired: true
  description: |+
    The unique identifier of defaultManagedAppProtection

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExpandProperty
  description: |+
    Expand related entities

  defaultValue: None
  position: Named
  aliases: Expand
  parameterValueGroup: ""
- type: <xref href="IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Property
  description: |+
    Select properties to be returned

  defaultValue: None
  position: Named
  aliases: Select
  parameterValueGroup: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary
name: Get-MgDeviceAppManagementDefaultManagedAppProtectionDeploymentSummary
description: |-
  Navigation property to deployment summary of the configuration.
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmanagementdefaultmanagedappprotectiondeploymentsummary
  schema: 2.0.0
