### YamlMime:PowershellCmdlet
summary: |-
  App configuration user status summary.

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  Please use Get-Help -Online.
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Get-MgBetaDeviceAppMgtMobileAppConfigurationUserStatusSummary?view=graph-powershell-beta
- text: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationuserstatussummary
  href: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationuserstatussummary
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Get-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary
name: Get-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary
description: |-
  App configuration user status summary.
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devices.corporatemanagement/get-mgdeviceappmgtmobileappconfigurationuserstatussummary
  schema: 2.0.0
