### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property targetedManagedAppConfigurations in deviceAppManagement

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  ALIASES

  Update-MgDeviceAppMgtTargetedManagedAppConfiguration

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `APPS <IMicrosoftGraphManagedMobileApp[]>`: List of apps to which the policy is deployed.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[MobileAppIdentifier <IMicrosoftGraphMobileAppIdentifier>]`: The identifier for a mobile app.
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Version <String>]`: Version of the entity.

  `ASSIGNMENTS <IMicrosoftGraphTargetedManagedAppPolicyAssignment[]>`: Navigation property to list of inclusion and exclusion groups to which the policy is deployed.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[Target <IMicrosoftGraphDeviceAndAppManagementAssignmentTarget>]`: Base type for assignment targets.
      - `[(Any) <Object>]`: This indicates any property can be added to this object.

  `BODYPARAMETER <IMicrosoftGraphTargetedManagedAppConfiguration>`: Configuration used to deliver a set of custom settings as-is to all users in the targeted security group
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[CustomSettings <IMicrosoftGraphKeyValuePair[]>]`: A set of string key and string value pairs to be sent to apps for users to whom the configuration is scoped, unalterned by this service
      - `[Name <String>]`: Name for this key-value pair
      - `[Value <String>]`: Value for this key-value pair
    - `[CreatedDateTime <DateTime?>]`: The date and time the policy was created.
    - `[Description <String>]`: The policy's description.
    - `[DisplayName <String>]`: Policy display name.
    - `[LastModifiedDateTime <DateTime?>]`: Last time the policy was modified.
    - `[Version <String>]`: Version of the entity.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[Apps <IMicrosoftGraphManagedMobileApp[]>]`: List of apps to which the policy is deployed.
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[MobileAppIdentifier <IMicrosoftGraphMobileAppIdentifier>]`: The identifier for a mobile app.
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Version <String>]`: Version of the entity.
    - `[Assignments <IMicrosoftGraphTargetedManagedAppPolicyAssignment[]>]`: Navigation property to list of inclusion and exclusion groups to which the policy is deployed.
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[Target <IMicrosoftGraphDeviceAndAppManagementAssignmentTarget>]`: Base type for assignment targets.
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[DeployedAppCount <Int32?>]`: Count of apps to which the current policy is deployed.
    - `[DeploymentSummary <IMicrosoftGraphManagedAppPolicyDeploymentSummary>]`: The ManagedAppEntity is the base entity type for all other entity types under app management workflow.
      - `[(Any) <Object>]`: This indicates any property can be added to this object.
      - `[Id <String>]`: The unique idenfier for an entity. Read-only.
      - `[ConfigurationDeployedUserCount <Int32?>]`: Not yet documented
      - `[ConfigurationDeploymentSummaryPerApp <IMicrosoftGraphManagedAppPolicyDeploymentSummaryPerApp[]>]`: Not yet documented
        - `[ConfigurationAppliedUserCount <Int32?>]`: Number of users the policy is applied.
        - `[MobileAppIdentifier <IMicrosoftGraphMobileAppIdentifier>]`: The identifier for a mobile app.
      - `[DisplayName <String>]`: Not yet documented
      - `[LastRefreshTime <DateTime?>]`: Not yet documented
      - `[Version <String>]`: Version of the entity.
    - `[IsAssigned <Boolean?>]`: Indicates if the policy is deployed to any inclusion groups or not.

  `CUSTOMSETTINGS <IMicrosoftGraphKeyValuePair[]>`: A set of string key and string value pairs to be sent to apps for users to whom the configuration is scoped, unalterned by this service
    - `[Name <String>]`: Name for this key-value pair
    - `[Value <String>]`: Value for this key-value pair

  `DEPLOYMENTSUMMARY <IMicrosoftGraphManagedAppPolicyDeploymentSummary>`: The ManagedAppEntity is the base entity type for all other entity types under app management workflow.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[ConfigurationDeployedUserCount <Int32?>]`: Not yet documented
    - `[ConfigurationDeploymentSummaryPerApp <IMicrosoftGraphManagedAppPolicyDeploymentSummaryPerApp[]>]`: Not yet documented
      - `[ConfigurationAppliedUserCount <Int32?>]`: Number of users the policy is applied.
      - `[MobileAppIdentifier <IMicrosoftGraphMobileAppIdentifier>]`: The identifier for a mobile app.
        - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[DisplayName <String>]`: Not yet documented
    - `[LastRefreshTime <DateTime?>]`: Not yet documented
    - `[Version <String>]`: Version of the entity.

  `INPUTOBJECT <IDevicesCorporateManagementIdentity>`: Identity Parameter
    - `[AndroidManagedAppProtectionId <String>]`: The unique identifier of androidManagedAppProtection
    - `[DefaultManagedAppProtectionId <String>]`: The unique identifier of defaultManagedAppProtection
    - `[DeviceCompliancePolicyStateId <String>]`: The unique identifier of deviceCompliancePolicyState
    - `[DeviceConfigurationStateId <String>]`: The unique identifier of deviceConfigurationState
    - `[DeviceInstallStateId <String>]`: The unique identifier of deviceInstallState
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DeviceManagementTroubleshootingEventId <String>]`: The unique identifier of deviceManagementTroubleshootingEvent
    - `[IosManagedAppProtectionId <String>]`: The unique identifier of iosManagedAppProtection
    - `[ManagedAppOperationId <String>]`: The unique identifier of managedAppOperation
    - `[ManagedAppPolicyId <String>]`: The unique identifier of managedAppPolicy
    - `[ManagedAppRegistrationId <String>]`: The unique identifier of managedAppRegistration
    - `[ManagedAppStatusId <String>]`: The unique identifier of managedAppStatus
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[ManagedDeviceMobileAppConfigurationAssignmentId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationAssignment
    - `[ManagedDeviceMobileAppConfigurationDeviceStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationDeviceStatus
    - `[ManagedDeviceMobileAppConfigurationId <String>]`: The unique identifier of managedDeviceMobileAppConfiguration
    - `[ManagedDeviceMobileAppConfigurationUserStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationUserStatus
    - `[ManagedEBookAssignmentId <String>]`: The unique identifier of managedEBookAssignment
    - `[ManagedEBookId <String>]`: The unique identifier of managedEBook
    - `[ManagedMobileAppId <String>]`: The unique identifier of managedMobileApp
    - `[MdmWindowsInformationProtectionPolicyId <String>]`: The unique identifier of mdmWindowsInformationProtectionPolicy
    - `[MobileAppAssignmentId <String>]`: The unique identifier of mobileAppAssignment
    - `[MobileAppCategoryId <String>]`: The unique identifier of mobileAppCategory
    - `[MobileAppId <String>]`: The unique identifier of mobileApp
    - `[TargetedManagedAppConfigurationId <String>]`: The unique identifier of targetedManagedAppConfiguration
    - `[TargetedManagedAppPolicyAssignmentId <String>]`: The unique identifier of targetedManagedAppPolicyAssignment
    - `[UserId <String>]`: The unique identifier of user
    - `[UserInstallStateSummaryId <String>]`: The unique identifier of userInstallStateSummary
    - `[VppTokenId <String>]`: The unique identifier of vppToken
    - `[WindowsDeviceMalwareStateId <String>]`: The unique identifier of windowsDeviceMalwareState
    - `[WindowsInformationProtectionAppLockerFileId <String>]`: The unique identifier of windowsInformationProtectionAppLockerFile
    - `[WindowsInformationProtectionPolicyId <String>]`: The unique identifier of windowsInformationProtectionPolicy
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphTargetedManagedAppConfiguration" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphTargetedManagedAppConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Update-MgBetaDeviceAppManagementTargetedManagedAppConfiguration?view=graph-powershell-beta
syntaxes:
- >-
  Update-MgDeviceAppManagementTargetedManagedAppConfiguration -TargetedManagedAppConfigurationId <String>

   [-AdditionalProperties <Hashtable>] [-Apps <IMicrosoftGraphManagedMobileApp[]>]

   [-Assignments <IMicrosoftGraphTargetedManagedAppPolicyAssignment[]>] [-CreatedDateTime <DateTime>]

   [-CustomSettings <IMicrosoftGraphKeyValuePair[]>] [-DeployedAppCount <Int32>]

   [-DeploymentSummary <IMicrosoftGraphManagedAppPolicyDeploymentSummary>] [-Description <String>]

   [-DisplayName <String>] [-Id <String>] [-IsAssigned] [-LastModifiedDateTime <DateTime>] [-Version <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementTargetedManagedAppConfiguration -TargetedManagedAppConfigurationId <String>

   -BodyParameter <IMicrosoftGraphTargetedManagedAppConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementTargetedManagedAppConfiguration -InputObject <IDevicesCorporateManagementIdentity>

   [-AdditionalProperties <Hashtable>] [-Apps <IMicrosoftGraphManagedMobileApp[]>]

   [-Assignments <IMicrosoftGraphTargetedManagedAppPolicyAssignment[]>] [-CreatedDateTime <DateTime>]

   [-CustomSettings <IMicrosoftGraphKeyValuePair[]>] [-DeployedAppCount <Int32>]

   [-DeploymentSummary <IMicrosoftGraphManagedAppPolicyDeploymentSummary>] [-Description <String>]

   [-DisplayName <String>] [-Id <String>] [-IsAssigned] [-LastModifiedDateTime <DateTime>] [-Version <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementTargetedManagedAppConfiguration -InputObject <IDevicesCorporateManagementIdentity>

   -BodyParameter <IMicrosoftGraphTargetedManagedAppConfiguration> [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedMobileApp" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Apps
  description: |+
    List of apps to which the policy is deployed.
    To construct, see NOTES section for APPS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphTargetedManagedAppPolicyAssignment" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Assignments
  description: |+
    Navigation property to list of inclusion and exclusion groups to which the policy is deployed.
    To construct, see NOTES section for ASSIGNMENTS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphTargetedManagedAppConfiguration" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Configuration used to deliver a set of custom settings as-is to all users in the targeted security group
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: CreatedDateTime
  description: |+
    The date and time the policy was created.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphKeyValuePair" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CustomSettings
  description: |+
    A set of string key and string value pairs to be sent to apps for users to whom the configuration is scoped, unalterned by this service
    To construct, see NOTES section for CUSTOMSETTINGS properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: DeployedAppCount
  description: |+
    Count of apps to which the current policy is deployed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedAppPolicyDeploymentSummary" data-throw-if-not-resolved="False" />
  name: DeploymentSummary
  description: |+
    The ManagedAppEntity is the base entity type for all other entity types under app management workflow.
    To construct, see NOTES section for DEPLOYMENTSUMMARY properties and create a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    The policy's description.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Policy display name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsAssigned
  description: |+
    Indicates if the policy is deployed to any inclusion groups or not.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastModifiedDateTime
  description: |+
    Last time the policy was modified.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetedManagedAppConfigurationId
  isRequired: true
  description: |+
    The unique identifier of targetedManagedAppConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Version
  description: |+
    Version of the entity.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Update-MgDeviceAppManagementTargetedManagedAppConfiguration
name: Update-MgDeviceAppManagementTargetedManagedAppConfiguration
description: |-
  Update the navigation property targetedManagedAppConfigurations in deviceAppManagement
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devices.corporatemanagement/update-mgdeviceappmanagementtargetedmanagedappconfiguration
  schema: 2.0.0
