### YamlMime:PowershellCmdlet
summary: |-
  Update the navigation property userStatusSummary in deviceAppManagement

  > [!NOTE]
  > To view the beta release of this cmdlet, view [Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary](/powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary?view=graph-powershell-beta)
module: Microsoft.Graph.Devices.CorporateManagement
notes: |-
  ALIASES

  Update-MgDeviceAppMgtMobileAppConfigurationUserStatusSummary

  COMPLEX PARAMETER PROPERTIES

  To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.


  `BODYPARAMETER <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary>`: Contains properties, inherited properties and actions for an MDM mobile app configuration user status summary.
    - `[(Any) <Object>]`: This indicates any property can be added to this object.
    - `[Id <String>]`: The unique idenfier for an entity. Read-only.
    - `[ConfigurationVersion <Int32?>]`: Version of the policy for that overview
    - `[ErrorCount <Int32?>]`: Number of error Users
    - `[FailedCount <Int32?>]`: Number of failed Users
    - `[LastUpdateDateTime <DateTime?>]`: Last update time
    - `[NotApplicableCount <Int32?>]`: Number of not applicable users
    - `[PendingCount <Int32?>]`: Number of pending Users
    - `[SuccessCount <Int32?>]`: Number of succeeded Users

  `INPUTOBJECT <IDevicesCorporateManagementIdentity>`: Identity Parameter
    - `[AndroidManagedAppProtectionId <String>]`: The unique identifier of androidManagedAppProtection
    - `[DefaultManagedAppProtectionId <String>]`: The unique identifier of defaultManagedAppProtection
    - `[DeviceCompliancePolicyStateId <String>]`: The unique identifier of deviceCompliancePolicyState
    - `[DeviceConfigurationStateId <String>]`: The unique identifier of deviceConfigurationState
    - `[DeviceInstallStateId <String>]`: The unique identifier of deviceInstallState
    - `[DeviceLogCollectionResponseId <String>]`: The unique identifier of deviceLogCollectionResponse
    - `[DeviceManagementTroubleshootingEventId <String>]`: The unique identifier of deviceManagementTroubleshootingEvent
    - `[IosManagedAppProtectionId <String>]`: The unique identifier of iosManagedAppProtection
    - `[ManagedAppOperationId <String>]`: The unique identifier of managedAppOperation
    - `[ManagedAppPolicyId <String>]`: The unique identifier of managedAppPolicy
    - `[ManagedAppRegistrationId <String>]`: The unique identifier of managedAppRegistration
    - `[ManagedAppStatusId <String>]`: The unique identifier of managedAppStatus
    - `[ManagedDeviceId <String>]`: The unique identifier of managedDevice
    - `[ManagedDeviceMobileAppConfigurationAssignmentId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationAssignment
    - `[ManagedDeviceMobileAppConfigurationDeviceStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationDeviceStatus
    - `[ManagedDeviceMobileAppConfigurationId <String>]`: The unique identifier of managedDeviceMobileAppConfiguration
    - `[ManagedDeviceMobileAppConfigurationUserStatusId <String>]`: The unique identifier of managedDeviceMobileAppConfigurationUserStatus
    - `[ManagedEBookAssignmentId <String>]`: The unique identifier of managedEBookAssignment
    - `[ManagedEBookId <String>]`: The unique identifier of managedEBook
    - `[ManagedMobileAppId <String>]`: The unique identifier of managedMobileApp
    - `[MdmWindowsInformationProtectionPolicyId <String>]`: The unique identifier of mdmWindowsInformationProtectionPolicy
    - `[MobileAppAssignmentId <String>]`: The unique identifier of mobileAppAssignment
    - `[MobileAppCategoryId <String>]`: The unique identifier of mobileAppCategory
    - `[MobileAppId <String>]`: The unique identifier of mobileApp
    - `[TargetedManagedAppConfigurationId <String>]`: The unique identifier of targetedManagedAppConfiguration
    - `[TargetedManagedAppPolicyAssignmentId <String>]`: The unique identifier of targetedManagedAppPolicyAssignment
    - `[UserId <String>]`: The unique identifier of user
    - `[UserInstallStateSummaryId <String>]`: The unique identifier of userInstallStateSummary
    - `[VppTokenId <String>]`: The unique identifier of vppToken
    - `[WindowsDeviceMalwareStateId <String>]`: The unique identifier of windowsDeviceMalwareState
    - `[WindowsInformationProtectionAppLockerFileId <String>]`: The unique identifier of windowsInformationProtectionAppLockerFile
    - `[WindowsInformationProtectionPolicyId <String>]`: The unique identifier of windowsInformationProtectionPolicy
inputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Graph.PowerShell.Models.IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary
  href: /powershell/module/Microsoft.Graph.Beta.Devices.CorporateManagement/Update-MgBetaDeviceAppManagementMobileAppConfigurationUserStatusSummary?view=graph-powershell-beta
syntaxes:
- >-
  Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary

   -ManagedDeviceMobileAppConfigurationId <String> [-AdditionalProperties <Hashtable>]

   [-ConfigurationVersion <Int32>] [-ErrorCount <Int32>] [-FailedCount <Int32>] [-Id <String>]

   [-LastUpdateDateTime <DateTime>] [-NotApplicableCount <Int32>] [-PendingCount <Int32>] [-SuccessCount <Int32>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary

   -ManagedDeviceMobileAppConfigurationId <String>

   -BodyParameter <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary> [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary

   -InputObject <IDevicesCorporateManagementIdentity> [-AdditionalProperties <Hashtable>]

   [-ConfigurationVersion <Int32>] [-ErrorCount <Int32>] [-FailedCount <Int32>] [-Id <String>]

   [-LastUpdateDateTime <DateTime>] [-NotApplicableCount <Int32>] [-PendingCount <Int32>] [-SuccessCount <Int32>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary

   -InputObject <IDevicesCorporateManagementIdentity>

   -BodyParameter <IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary> [-WhatIf] [-Confirm]

   [<CommonParameters>]
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AdditionalProperties
  description: |+
    Additional Parameters

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IMicrosoftGraphManagedDeviceMobileAppConfigurationUserSummary" data-throw-if-not-resolved="False" />
  name: BodyParameter
  isRequired: true
  description: |+
    Contains properties, inherited properties and actions for an MDM mobile app configuration user status summary.
    To construct, see NOTES section for BODYPARAMETER properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ConfigurationVersion
  description: |+
    Version of the policy for that overview

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ErrorCount
  description: |+
    Number of error Users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: FailedCount
  description: |+
    Number of failed Users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  description: |+
    The unique idenfier for an entity.
    Read-only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="IDevicesCorporateManagementIdentity" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Identity Parameter
    To construct, see NOTES section for INPUTOBJECT properties and create a hash table.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: LastUpdateDateTime
  description: |+
    Last update time

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ManagedDeviceMobileAppConfigurationId
  isRequired: true
  description: |+
    The unique identifier of managedDeviceMobileAppConfiguration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NotApplicableCount
  description: |+
    Number of not applicable users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PendingCount
  description: |+
    Number of pending Users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: SuccessCount
  description: |+
    Number of succeeded Users

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.Graph.Devices.CorporateManagement.Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary
name: Update-MgDeviceAppManagementMobileAppConfigurationUserStatusSummary
description: |-
  Update the navigation property userStatusSummary in deviceAppManagement
metadata:
  external help file: Microsoft.Graph.Devices.CorporateManagement-help.xml
  Module Name: Microsoft.Graph.Devices.CorporateManagement
  online version: https://learn.microsoft.com/powershell/module/microsoft.graph.devices.corporatemanagement/update-mgdeviceappmanagementmobileappconfigurationuserstatussummary
  schema: 2.0.0
